### ISSUE TITLE
No courses Found 

### ISSUE THREAD

**Issue by vedantsingh650** [heliomarpm/udemy-downloader-gui#10]
After the fix of commit id b9e51c64da5e6317cddce5595d9ff19337f64480 "Fixed critical error" 
I download the software and Login with the Access Token .
Getting response "No courses Found" .

![Screenshot (124)](https://user-images.githubusercontent.com/26855621/146966066-924468fd-24ba-4632-a84c-ce8eb9fa17fa.png)
 .

**Comment by heliomarpm** [comment]
I could not reproduce this error, please restart Udeler and ensure that you are enrolled in some course within the platform
