### ISSUE TITLE
When trying to download the subtitle, it shows an error

### ISSUE THREAD

**Issue by INV1NCIBL3** [heliomarpm/udemy-downloader-gui#104]
### Udeler | Udemy Course Downloader

1.11.2

### Running as Business Account

- [ ] Yes

### Steps to reproduce

After downloading a few videos, when it comes time to download subtitles **it gets stuck like this**. I have to exit and re-open again and again, this way I can download 1/2 GB with difficulty. I don't dare to download 10/15 GB (+) like this! I thought that I would go to sleep with a download at night and wake up in the morning to see that the download is complete, but it is not possible!
![photo_2023-03-24_12-18-31](https://user-images.githubusercontent.com/114050608/227495731-f96bce6e-3684-4849-bc2d-8dfcf0d2be44.jpg)

### ✔️ Expected Behavior

So that I can easily download 10/15 GB (+) file without any error. No problem downloading my subtitles!
And the error is showing during the download of the video, after restarting the app, the file is no longer in the download option, I have to search again! You will see that this problem does not exist.
Overall, this is a good one.

### ❌ Actual Behavior / Steps to Reproduce

Just login & download your desire file then Chill.

**Comment by heliomarpm** [comment]
if you don't download subtitles, do all videos download?

**Comment by INV1NCIBL3** [comment]
> if you don't download subtitles, do all videos download?
After turned off subtitle, still facing this problem :)
![Screenshot 2023-03-25 185539](https://user-images.githubusercontent.com/114050608/227718681-c78501a7-952a-4ff1-a613-b0ab04aec806.png)
![Screenshot 2023-03-25 185624](https://user-images.githubusercontent.com/114050608/227718682-2a6bbf25-d239-4d2e-b143-688626445e84.png)

**Comment by heliomarpm** [comment]
> > if you don't download subtitles, do all videos download?
> After turned off subtitle, still facing this problem :)
> ![Screenshot 2023-03-25 185539](https://user-images.githubusercontent.com/114050608/227718681-c78501a7-952a-4ff1-a613-b0ab04aec806.png)
> ![Screenshot 2023-03-25 185624](https://user-images.githubusercontent.com/114050608/227718682-2a6bbf25-d239-4d2e-b143-688626445e84.png)
> 

Thanks. 
I will check

**Comment by INV1NCIBL3** [comment]
[udeler_logger.txt](https://github.com/heliomarpm/udemy-downloader-gui/files/11074928/udeler_logger.txt)

**Comment by heliomarpm** [comment]
check new version
