### ISSUE TITLE
Unable to download the course

### ISSUE THREAD

**Issue by huisson** [heliomarpm/udemy-downloader-gui#106]
### Udeler | Udemy Course Downloader

1.1.10 Mac x64

### Running as Business Account

- [ ] Yes

### Steps to reproduce

unable to download the course afte
1. course list created
2. choose the subtitle for the course
then see the pic
![截圖 2023-03-26 10 03 45](https://user-images.githubusercontent.com/104963127/227751287-a4fd9e2d-68bf-4bf8-8e3d-6b0913cd4bd4.jpg)

### ✔️ Expected Behavior

Just download smoothly..

### ❌ Actual Behavior / Steps to Reproduce

1. course list created--OK
2. choose the subtitle for the course--OK
enter download status --Stop
(already chosen the skip DRM in setting)
![CleanShot 2023-03-26 at 10 10 24@2x](https://user-images.githubusercontent.com/104963127/227751452-e8da3733-c510-4559-b7d6-d6498a5d4787.jpg)

**Comment by huisson** [comment]
![CleanShot 2023-04-02 at 19 52 52@2x](https://user-images.githubusercontent.com/104963127/229351105-ade8ecd3-27cf-4e76-a37d-cece2a400b1d.jpg)
After update to 1.12.1 ~Still cant download the courses

**Comment by heliomarpm** [comment]
Send me the Logger please

**Comment by heliomarpm** [comment]
> ![CleanShot 2023-04-02 at 19 52 52@2x](https://user-images.githubusercontent.com/104963127/229351105-ade8ecd3-27cf-4e76-a37d-cece2a400b1d.jpg)
> After update to 1.12.1 ~Still cant download the courses

Send me the Logger please

**Comment by huisson** [comment]
https://www.loom.com/share/cbf01f663c74467b892b5ed8b3866e2d
I could not find any logger,  please see the loom video for logger is unable to open ..

**Comment by huisson** [comment]
after reinstall 1.12.1-->No course found
![CleanShot 2023-04-07 at 10 27 26@2x](https://user-images.githubusercontent.com/104963127/230528411-c3f4f969-861b-46ca-808a-a2d4f443d80a.jpg)

**Comment by huisson** [comment]
After Re-Login I got the courses list successfully-->pic.
![CleanShot 2023-04-07 at 10 40 45@2x](https://user-images.githubusercontent.com/104963127/230530345-ad1955fc-c5b2-4dcf-89cf-66ad059e8427.jpg)
**Question1**. Should I install 1.8.2(the old version) in advance?

**Comment by Pape45** [comment]
Same problem on m1 macbook air. Can't download course ( stay at 0% )

**Comment by heliomarpm** [comment]
Sorry friend, I can't reproduce this error with the courses I have.
If you can email me your token, maybe I found the problem with that same course. 🫤

Anyway, I keep looking for a reason for this, I hope you understand.

> ![CleanShot 2023-04-02 em 19 52 52@2x](https://user-images.githubusercontent.com/104963127/229351105-ade8ecd3-27cf-4e76-a37d-cece2a400b1d.jpg) Após a atualização para 1.12.1 ~Ainda não consigo baixar os cursos

Sorry friend, I can't reproduce this error with the courses I have.
If you can email me your token, maybe I found the problem with that same course. 🫤

Can you download any other course? Do you think it's possible that your connection is blocking the download? Have you tried using any vpn, to test?

Anyway, I keep looking for a reason for this, I hope you understand.

**Comment by heliomarpm** [comment]
> Após o Re-Login eu tenho a lista de cursos com sucesso -->pic. O registrador ainda está vazio.
> 
> ![CleanShot 2023-04-07 em 10 40 45@2x](https://user-images.githubusercontent.com/104963127/230530345-ad1955fc-c5b2-4dcf-89cf-66ad059e8427.jpg) **Pergunta 1**. Devo instalar a versão 1.8.2 (a versão antiga) com antecedência?

This error was much more common in older versions, but if it worked please let me know, it might help me to find the cause in recent versions

**Comment by heliomarpm** [comment]
Check the new version
