### ISSUE TITLE
 i cannot download the course securired by DRM

### ISSUE THREAD

**Issue by thanhtam0101** [heliomarpm/udemy-downloader-gui#108]
### Provide a description of requested docs changes

hi everyone
could you please update this app

**Comment by heliomarpm** [comment]
This app does not download DRM protected videos
As described in:
https://github.com/heliomarpm/udemy-downloader-gui#warning

Alternatively, you can try here
https://github.com/heliomarpm/udemy-downloader-gui/issues/13#issuecomment-1125137108
