### ISSUE TITLE
1080p Video download Support

### ISSUE THREAD

**Issue by ByEzel93** [heliomarpm/udemy-downloader-gui#11]
Hello, first of all, thank you for continuing the project. We cannot download videos in 1080p format. Could you please bring 1080p support?

**Comment by heliomarpm** [comment]
> Hello, first of all, thank you for continuing the project. We cannot download videos in 1080p format. Could you please bring 1080p support?

Hello, some courses do not offer download in 1080p, select the highest option to get the best resolution available

**Comment by ByEzel93** [comment]
> > Merhaba, öncelikle projeye devam ettiğiniz için teşekkür ederiz. Videoları 1080p formatında indiremiyoruz. Lütfen 1080p desteği getirir misiniz?
> 
> Merhaba, bazı kurslar 1080p'de indirme sunmuyor, mevcut en iyi çözünürlüğü elde etmek için en yüksek seçeneği seçin

Tekrardan Merhaba, benim satın aldığım kurslar 1080p sunuyor. udemy de 1080p izleyebiliyorum. ama programda 1080p yi seçince bile 720p olarak indiriyor
