### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by rlb303** [heliomarpm/udemy-downloader-gui#114]
After i log in either through credentials or acess token, all i get is a blank page. 

![image](https://user-images.githubusercontent.com/40693675/232549318-319001a6-9809-4183-8310-fc2abefebd6b.png)

I closed and opened the app and now there are some errors in the Logger, don't know if it's related: 

uncaughtException
TypeError: Cannot read property 'checkNewVersion' of undefined at loadSettings (file:///C:/Users/renan/AppData/Local/Programs/udeler/resources/app.asar/assets/js/app.js:1497:91) at HTMLAnchorElement. (file:///C:/Users/renan/AppData/Local/Programs/udeler/resources/app.asar/assets/js/app.js:1416:3) at HTMLAnchorElement.dispatch (C:\Users\renan\AppData\Local\Programs\udeler\resources\app.asar\node_modules\jquery\dist\jquery.js:5494:27) at HTMLAnchorElement.elemData.handle (C:\Users\renan\AppData\Local\Programs\udeler\resources\app.asar\node_modules\jquery\dist\jq

**Comment by schousda** [comment]
I had to go to the settings and i filled all options with a correct value. After a restart i could start to download the files.

**Comment by rlb303** [comment]
Thanks! That actually solved the problem, no more error in logger aswell.

**Comment by Qleoz12** [comment]
> I had to go to the settings and i filled all options with a correct value. After a restart i could start to download the files.

where is the settings file ?

**Comment by rlb303** [comment]
> > I had to go to the settings and i filled all options with a correct value. After a restart i could start to download the files.
> 
> where is the settings file ?

It's not a file. It's the "Settings" tab on the left of the GUI.

**Comment by Qleoz12** [comment]
I donwloaded the Udeler_Portable-v1.12.1_win-x64.exe it works like a charm, i will check how set the value at settings tab

**Comment by heliomarpm** [comment]
Thanks for the help guys, that's how it has to be.  Correction is scheduled for next Sunday, April 23

**Comment by heliomarpm** [comment]
Check the latest version

**Comment by manuelgomez7193** [comment]
It's working perfectly. thank you @heliomarpm!

**Comment by rlb303** [comment]
Tested the latest v1.12.4 on Windows 11 and the problem is definitely solved! 
But was unable to run it on Ubuntu 23.04 (running on VirtualBox 7) will create another thread with the errors to not pollute this one.

**Comment by heliomarpm** [comment]
> Tested the latest v1.12.4 on Windows 11 and the problem is definitely solved! But was unable to run it on Ubuntu 23.04 (running on VirtualBox 7) will create another thread with the errors to not pollute this one.

Thanks, I'm not a Linux user, maybe I need a little more detail
