### ISSUE TITLE
Getting ENOENT: no such file or directory on mp4 files (probably a path issue for special characters on tittles)

### ISSUE THREAD

**Issue by alejokalderon** [heliomarpm/udemy-downloader-gui#119]
Hi,

First of all thank you for supporting this great tool.

I'm trying to download some videos but I'm getting this error with one of them:

Error ENOENT: no such file or directory, unlink '(my path)'.

I'm currently using Max OSX Ventura with a M1 chip. So probably a good way is to have the option to skip the corrupt or the videos that are not able to download and continue with the next ones so we download will not be blocked, at the end we could try to find the corrupt ones and download those manually or something like that because at this point I'm trying to download a 200 videos course but I'm blocked on the 4 video so the first 3 are perfect.

Thank you in advance.

Regards!

**Comment by alejokalderon** [comment]
Quick update, the course that I'm trying to download is in Spanish, and probably is an special character issue on the storage path (like an ñ or something like that because I also tried with a course in English and it failed due to the video title used parenthesis on it, probably a good way is to do a replace on this kind of special characters, even the spaces and whatever for underscores or something like that.

**Comment by heliomarpm** [comment]
> Quick update, the course that I'm trying to download is in Spanish, and probably is an special character issue on the storage path (like an ñ or something like that) because I also tried with a course in English and it failed due to the video title used parenthesis on it, probably a good way is to do a replace on this kind of special characters, even the spaces and whatever for underscores or something like that.

Special characters shouldn't be a problem, because the tool removes these.
Have you checked your location settings for downloads?
If possible send me the error shown in the logger section

**Comment by alejokalderon** [comment]
Hi @heliomarpm thank you for your quick reply.

I'm downloading in /opt/udemy folder, I added full permissions to this folder (777) just for testing purposes, I'm attaching the log for error in both courses


<img width="1091" alt="Screenshot 2023-04-23 at 10 44 23 PM" src="https://user-images.githubusercontent.com/8851716/233895489-f63e16f1-90c5-4ac0-a00d-689dccd1bfce.png">

**Comment by Qleoz12** [comment]
errorDownload
Error: ENOENT: no such file or directory, unlink 'D:\downloads\Java Data Structures & Algorithms + 76 CODING EXERCISES\1. Introduction\3. Code Editor.mp4'
errorDownload
The .mtd file is corrupt. Start a new download.

> > Quick update, the course that I'm trying to download is in Spanish, and probably is an special character issue on the storage path (like an ñ or something like that) because I also tried with a course in English and it failed due to the video title used parenthesis on it, probably a good way is to do a replace on this kind of special characters, even the spaces and whatever for underscores or something like that.
> 
> Special characters shouldn't be a problem, because the tool removes these. Have you checked your location settings for downloads? If possible send me the error shown in the logger section

i tryied las version  and im also getting 

errorDownload
Error: ENOENT: no such file or directory, unlink 'D:\downloads\Java Data Structures & Algorithms + 76 CODING EXERCISES\1. Introduction\3. Code Editor.mp4'
errorDownload
The .mtd file is corrupt. Start a new download. (where is this file or how reset this file)

**Comment by heliomarpm** [comment]
> Hi @heliomarpm thank you for your quick reply.
> 
> I'm downloading in /opt/udemy folder, I added full permissions to this folder (777) just for testing purposes, I'm attaching the log for error in both courses
> 
> 
> <img width="1091" alt="Screenshot 2023-04-23 at 10 44 23 PM" src="https://user-images.githubusercontent.com/8851716/233895489-f63e16f1-90c5-4ac0-a00d-689dccd1bfce.png">
> 
> 

close udeler go to the download folder and delete all .mtd files and start over

**Comment by heliomarpm** [comment]
> > > Quick update, the course that I'm trying to download is in Spanish, and probably is an special character issue on the storage path (like an ñ or something like that) because I also tried with a course in English and it failed due to the video title used parenthesis on it, probably a good way is to do a replace on this kind of special characters, even the spaces and whatever for underscores or something like that.
> > 
> > Special characters shouldn't be a problem, because the tool removes these. Have you checked your location settings for downloads? If possible send me the error shown in the logger section
> 
> i tryied las version  and im also getting 
> 
> errorDownload
> Error: ENOENT: no such file or directory, unlink 'D:\downloads\Java Data Structures & Algorithms + 76 CODING EXERCISES\1. Introduction\3. Code Editor.mp4'
> errorDownload
> The .mtd file is corrupt. Start a new download. (where is this file or how reset this file)

close udeler go to the download folder and delete all .mtd files and start over
