### ISSUE TITLE
Cannot download!   Stuck at "Building Course Data"

### ISSUE THREAD

**Issue by testmodem** [heliomarpm/udemy-downloader-gui#121]
Hello I am trying to downoad a course from udemy. 
This get stuck at "building Course Data".

Please advise.

**Comment by Kenworld** [comment]
SAME

**Comment by heliomarpm** [comment]
Can you please elaborate a little more?

Which version are you using?
Which course? Do you have a log? What settings are you using?

**Comment by kkkai-24** [comment]
Also experiencing the same, using the latest version. 
![image](https://user-images.githubusercontent.com/132024682/235015673-d5cef12a-8d04-4387-8cf6-3ee1675178ac.png)
![image](https://user-images.githubusercontent.com/132024682/235015707-1e8c306a-d252-445d-afe6-61610fb0d960.png)

**Comment by rsathishtechit** [comment]
Any update on the fix?

**Comment by heliomarpm** [comment]
This is a really hard problem to reproduce.
Does it happen with all courses or just some?

**Comment by heliomarpm** [comment]
> Any update on the fix?

investigating

**Comment by heliomarpm** [comment]
> Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
>     at app.js:615
> (anonymous) @ app.js:615
> Promise.catch (async)
> getLecture @ app.js:614
> (anonymous) @ app.js:620
> each @ D:\Github\udemy-downloader-gui\node_modules\jquery\dist\jquery.js:385
> (anonymous) @ app.js:402
> Promise.then (async)
> downloadButtonClick @ app.js:370
> (anonymous) @ app.js:330
> dispatch @ D:\Github\udemy-downloader-gui\node_modules\jquery\dist\jquery.js:5494
> elemData.handle @ D:\Github\udemy-downloader-gui\node_modules\jquery\dist\jquery.js:5298
> Don't know if this well help or not? Also it doesn't see any of the videos I'm trying to download as DRM protected and It can see all of them

What the course?

**Comment by xStreeme** [comment]
Same here. Latest version, latest macOS! So far unable to download any of the courses in my library.

**Comment by heliomarpm** [comment]
Guys, just to make it clear, the inability to download by DRM Protection is not an error, in these cases the videos will not be downloaded at all.
As for the problem with loading data getting stuck, I need some course names to help with the investigation, this is a difficult problem to reproduce, most of the time I just need to restart the tool, testing with courses where the problem occurs frequently may I hope I find the cause.

**Comment by trinhchien** [comment]
I encounter a similar issue when tried to download this course https://www.udemy.com/course/developer-to-architect/learn/lecture/24350002#overview.
Does this tool depend on the type of Udemy account (personal plan, business account, etc.)?

**Comment by testmodem** [comment]
failing to download the following : 

https://www.udemy.com/course/100-days-of-code/

Cannot download ..  This get stuck at "building Course Data".

**Comment by heliomarpm** [comment]
> I encounter a similar issue when tried to download this course https://www.udemy.com/course/developer-to-architect/learn/lecture/24350002#overview. Does this tool depend on the type of Udemy account (personal plan, business account, etc.)?

yes, you need an active account and be enrolled in the desired course

**Comment by heliomarpm** [comment]
> 

The videos in this course cannot be downloaded due to DRM protection, but I had no problems starting the download.

I will continue looking for the cause of the personal problem.

![BuildingData](https://user-images.githubusercontent.com/13087389/236334682-e2b6a271-121e-4b68-b372-e30dea68771f.gif)

**Comment by xStreeme** [comment]
Among others I tried with this free one.
https://www.udemy.com/share/101to23@RYa_lRaYafAPG9Y1KxR19wFy0xl_uESQWWDTDcgeDf0ssPH56-v4CAlflVGK3ZuWOQ==/

Stuck in building. Hope that helps.

**Comment by jmgomez1986** [comment]
I have the same problem. It stays in the "Building data" state and never downloads the course, I want to download courses from a Business account. I am using version 1.12.4

**Comment by snikolay** [comment]
I have the same error, and not one course out of 70 was not downloaded. After I changed the language and pressed the save button in the settings, restarted, everything started downloading. I returned the old language, and everything is downloaded, so I think it's the save settings button.

![2023-05-23_09-02-32](https://github.com/heliomarpm/udemy-downloader-gui/assets/20343866/e1a71868-b158-4f0a-b745-90e6fd4be380)

**Comment by xStreeme** [comment]
> I have the same error, and not one course out of 70 was not downloaded. After I changed the language and pressed the save button in the settings, restarted, everything started downloading. I returned the old language, and everything is downloaded, so I think it's the save settings button.
> 
> ![2023-05-23_09-02-32](https://user-images.githubusercontent.com/20343866/240148420-e1a71868-b158-4f0a-b745-90e6fd4be380.png)

It sounds right, dude! Following your advice I clicked on the settings tab, saved them (without making any change, in my case), back to the courses list and…it worked well!
Congrats!

**Comment by heliomarpm** [comment]
check new version 
https://github.com/heliomarpm/udemy-downloader-gui/releases/tag/v1.12.5
