### ISSUE TITLE
Sound damage when downloading videos with a resolution of 1080

### ISSUE THREAD

**Issue by suleimanovs** [heliomarpm/udemy-downloader-gui#122]
### Description of the new feature / enhancement

When I download a course with a resolution of 1080, then with the sound of the proyulema. Every 10 seconds there is an interference, that is, the sound freezes. I tried to download the same course with a resolution of 720, then there are no problems with the sound. Please tell me, are you already aware of this problem?

### Scenario when this would be used?

When I download a course with a resolution of 1080

**Comment by heliomarpm** [comment]
It seems to me an isolated problem, what is the name of the course?

**Comment by huda1237** [comment]
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/65228809/f5b58190-3275-42df-ac78-5cfe669d6f95)


Why does this error occur after using version 1.12.4 or 1.12.3

**Comment by heliomarpm** [comment]
> ![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/65228809/f5b58190-3275-42df-ac78-5cfe669d6f95)
> 
> 
> Why does this error occur after using version 1.12.4 or 1.12.3

it's not a version error.  Udemy has been protecting all its paid courses with this protection, it is possible that you have downloaded some course in the past, which is not possible today.

**Comment by suleimanovs** [comment]
> Мне кажется изолированная проблема, как называется курс?

https://www.udemy.com/share/1087uy3@_sKxPT7RU5H2JSU42D19E4pvV7uDxU9xXrmCyIxuFm8Me2T4Zmk6N2Ts_eLSL7ROgw==/

https://www.udemy.com/share/1056N43@K368QGkC4KFNUA3M72IUfOXx8walC8oXFqpk_cSG8zGzS7tcZljlQjCqAGmVunZxVg==/

I think this is a global problem and does not depend on which course, I can throw you one downloaded video with a resolution of 1080 so that you can hear what's with the sound

**Comment by heliomarpm** [comment]
check new version 
https://github.com/heliomarpm/udemy-downloader-gui/releases/tag/v1.12.5

**Comment by ahmedelsheikh2012** [comment]
> > ![image](https://user-images.githubusercontent.com/65228809/238138316-f5b58190-3275-42df-ac78-5cfe669d6f95.png)
> > Why does this error occur after using version 1.12.4 or 1.12.3
> 
> it's not a version error. Udemy has been protecting all its paid courses with this protection, it is possible that you have downloaded some courses in the past, which is not possible today.

please how can i download DRM Protected video and solve this error... now most of the courses are protected

**Comment by suleimanovs** [comment]
Bug fixed! thank you!

**Comment by huda1237** [comment]
> > ![image](https://user-images.githubusercontent.com/65228809/238138316-f5b58190-3275-42df-ac78-5cfe669d6f95.png)
> > Why does this error occur after using version 1.12.4 or 1.12.3
> 
> it's not a version error. Udemy has been protecting all its paid courses with this protection, it is possible that you have downloaded some course in the past, which is not possible today.

tanks
