### ISSUE TITLE
Downloading stops and gives an error

### ISSUE THREAD

**Issue by chococlat** [heliomarpm/udemy-downloader-gui#128]
### Udeler | Udemy Course Downloader

v1.12.4

### Account Type?

Business

### Steps to reproduce

On windows, with setup(x64)version 1.12.4, after download has started, and some files are downloaded, the process abruptely stops and gives an error 
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/109074987/2317dd06-a319-4bc1-af50-6a1e95984677)

On the logs I get 2 messages.
The first one:
`Invalid file path: C:\/LPI Linux Essentials (010-160) Complete Course and Exams/3. Open Source Applications/1. What is Open Source.mp4.mtd` 
The second one:
`Error: ENOENT: no such file or directory, unlink 'C:\LPI Linux Essentials (010-160) Complete Course and Exams\3. Open Source Applications\1. What is Open Source.mp4'`

I notice that the direction of the slash is incongruent and I am starting to think that this could be the problem. Of course it's not finding nothing in C:\\/...

Similarly if I change the path of the downloads :
First error:
`Invalid file path: C:\Users\acecc\Desktop\UDEMY/CompTIA Cloud Essentials+ (CL0-002) Complete Course & Exam/2. Cloud Principles/4. IaaS (OBJ. 1.1).mp4.mtd`
Second error:
`Error: ENOENT: no such file or directory, unlink 'C:\Users\acecc\Desktop\UDEMY\CompTIA Cloud Essentials+ (CL0-002) Complete Course & Exam\2. Cloud Principles\4. IaaS (OBJ. 1.1).mp4'
`
The errors are the same, and similarly there is this change of direction of the slashes, making me think that this is the problem.

### ✔️ Expected Behavior

Expecting to work

### ❌ Actual Behavior / Steps to Reproduce

.

**Comment by heliomarpm** [comment]
check new version 
https://github.com/heliomarpm/udemy-downloader-gui/releases/tag/v1.12.5

**Comment by UdelerFannumber1** [comment]
hey men , good work , but i happend again with the update but now it shows this

![udelerissue 2](https://github.com/heliomarpm/udemy-downloader-gui/assets/134817719/45aeab95-860b-4c86-889e-42e06c9cf343)
![udelerissue](https://github.com/heliomarpm/udemy-downloader-gui/assets/134817719/14ae05d5-5f41-4075-81b6-51b2d80e3bf4)

**Comment by UdelerFannumber1** [comment]
could it be udemy fighting back ? lol

**Comment by UdelerFannumber1** [comment]
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/134817719/eb1b604c-da90-4cb5-b626-84185fa71708)

**Comment by UdelerFannumber1** [comment]
keep happening
