### ISSUE TITLE
Error 429 (too many requests)

### ISSUE THREAD

**Issue by UdelerFannumber1** [heliomarpm/udemy-downloader-gui#129]
### Udeler | Udemy Course Downloader

v1.12.5

### Account Type?

Personal

### Steps to reproduce

it stop Dowloading 
![udelerissue 2](https://github.com/heliomarpm/udemy-downloader-gui/assets/134817719/1e8a7ff2-0950-4032-910e-0df3217b8c91)
![udelerissue](https://github.com/heliomarpm/udemy-downloader-gui/assets/134817719/5bbd2ec3-67be-4281-b98a-babf39c5810b)

### ✔️ Expected Behavior

to end download 

### ❌ Actual Behavior / Steps to Reproduce

i think it is blocking my IP or something

**Comment by UdelerFannumber1** [comment]
could it be Udemy Fighting back ?

**Comment by UdelerFannumber1** [comment]
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/134817719/e94e6748-d7db-4cdb-bbc7-80c9ce54713e)

**Comment by UdelerFannumber1** [comment]
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/134817719/40d3f05c-139a-4aa9-bf0b-c280f2707b0d)

**Comment by heliomarpm** [comment]
This error happens when many requests are being made at the same time, try to download one course at a time

**Comment by UdelerFannumber1** [comment]
still the same ...

**Comment by UdelerFannumber1** [comment]
still persist , does not want to download

**Comment by heliomarpm** [comment]
> still persist , does not want to download 

Is it the same error 429?
I can't reproduce

**Comment by UdelerFannumber1** [comment]
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/134817719/a34ee99e-d86b-48d6-8e61-72e61f677d1a)

![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/134817719/2a8d5c5f-80a6-41f5-8cec-84e9a97fd830)

**Comment by UdelerFannumber1** [comment]
still persist in not letting me download ...i blame udemy lol

**Comment by UdelerFannumber1** [comment]
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/134817719/908ca6c0-ae47-4348-9278-d3301e6dc81d)

**Comment by heliomarpm** [comment]
Check new version.
If this issue remains, please reopen this issue.
