### ISSUE TITLE
videoQuality.toLowerCase is not a function

### ISSUE THREAD

**Issue by abdulkhaliquem9** [heliomarpm/udemy-downloader-gui#130]
### Udeler | Udemy Course Downloader

Version 1.12.5

### Account Type?

Personal

### Steps to reproduce

after clicking the download icon below the course

### ✔️ Expected Behavior

extract list and download

### ❌ Actual Behavior / Steps to Reproduce

1.Go to app
2.Search the course
3.From the Search list, I got only one video in the search list 
3. click the download button & **BOOM ERROR!!**
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/27613442/23c81eb0-114f-4ade-b799-b3a6bf1c0104)

![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/27613442/7e4529de-9a61-4268-a29a-c9f1b265bf79)

**Comment by abdulkhaliquem9** [comment]
for my account I'm getting a boolean value in videoQuality instead of a string
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/27613442/e351aab0-4d59-408e-90be-2b27dc76d2d3)
@heliomarpm

**Comment by heliomarpm** [comment]
> for my account I'm getting a boolean value in **videoQuality** instead of a string 
> I'm able to download after commenting the switch block `switch (videoQuality.toLowerCase())`
> @heliomarpm 
> 
> ![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/27613442/e351aab0-4d59-408e-90be-2b27dc76d2d3)
> 

Yes. fix is on the way

**Comment by heliomarpm** [comment]
Check new version
