### ISSUE TITLE
getting DRM Protected issue

### ISSUE THREAD

**Issue by abdulkhaliquem9** [heliomarpm/udemy-downloader-gui#131]
### Udeler | Udemy Course Downloader

Version 1.12.5

### Account Type?

Business

### Steps to reproduce

open the app and search a video tutorial
click download button & you will see this error
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/27613442/a424e6f7-411b-4c03-93df-063f72f38b7a)
****

### ✔️ Expected Behavior

click the download button and download the videos.

### ❌ Actual Behavior / Steps to Reproduce

Go To the app
1. search for a course
2. click on the download button and you will see the DRM error

![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/27613442/133b2357-8097-417c-b368-8632c70ab518)

**Comment by heliomarpm** [comment]
isn't error
