### ISSUE TITLE
DRM Protected vedio course 

### ISSUE THREAD

**Issue by ahmedelsheikh2012** [heliomarpm/udemy-downloader-gui#132]
### Udeler | Udemy Course Downloader

1.12.6

### Account Type?

Personal

### Steps to reproduce

i can not download  any course that conation DRM Protected veido 
such this course 
https://www.udemy.com/course/planning-and-control-with-oracle-primavera-p6-ppm_eight_point_three/learn/lecture/16716264?start=225#overview

i need your help please. 

### ✔️ Expected Behavior

I expect you can sucn features to download DRM courses  

### ❌ Actual Behavior / Steps to Reproduce

...

**Comment by heliomarpm** [comment]
#13
