### ISSUE TITLE
Contains DRM protection & cannot be downloaded error

### ISSUE THREAD

**Issue by laxapatiakshaylearning** [heliomarpm/udemy-downloader-gui#133]
### Udeler | Udemy Course Downloader

1.12.6

### Account Type?

Personal

### Steps to reproduce

[](url)
![drm-protection-error](https://github.com/heliomarpm/udemy-downloader-gui/assets/85331372/f08dd82d-abf2-4107-b3da-bf489e3bd5c9)

### ✔️ Expected Behavior

Downloading Course with DRM protection

### ❌ Actual Behavior / Steps to Reproduce

1 navigate to couse and click on download

**Comment by ahmedelsheikh2012** [comment]
me to have the same problem and  i did find any soluations
