### ISSUE TITLE
Dont Show List Courses

### ISSUE THREAD

**Issue by pinguim16** [heliomarpm/udemy-downloader-gui#134]
### Udeler | Udemy Course Downloader

1.12.6

### Account Type?

Business

### Steps to reproduce

App dont show list courses 
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/8548495/7b60a117-f7e4-428b-b834-e3043a1e8285)

Log:
```
22/06/2023 15:26:16 - Não foi encontrado nenhum curso: <p>Esta conta foi identificada sem um plano de assinatura<br/>Se estiver errado, mude o modo de busca e tente novamente<div class="ui fluid buttons"><button class='ui primary button change-search-mode' onclick='toggleSubscriber()'>Alterar modo de pesquisa</button></div></p>
22/06/2023 15:25:39 - Não foi encontrado nenhum curso: <p>Esta conta foi identificada sem um plano de assinatura<br/>Se estiver errado, mude o modo de busca e tente novamente<div class="ui fluid buttons"><button class='ui primary button change-search-mode' onclick='toggleSubscriber()'>Alterar modo de pesquisa</button></div></p>

```

### ✔️ Expected Behavior

![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/8548495/205ec889-8a9c-4898-8e64-de45ad07f62a)

### ❌ Actual Behavior / Steps to Reproduce

1. Log Application by token
2. App show message the upload image and logs

**Comment by heliomarpm** [comment]
Seu usuário é assinante ou compra curso avulso? Chegou a clicar nesse botão azul, ele alterna entre esses tipos de conta para realizar a pesquisa

**Comment by heliomarpm** [comment]
Opa acabei de perceber que vc usou o token para se logar, obrigado por detalhar.

Bom, sua conta sendo Business, primeiramente vc precisa ativar a opção de business, preencher o subdomínio e depois informar o token

**Comment by pinguim16** [comment]
Obrigado, creio que errei no login, agora dps de realizar o procedimento que falou funcionou.
Me desculpe pela issue.
