### ISSUE TITLE
Is there a Download Speed Limit?

### ISSUE THREAD

**Issue by Nickyg001** [heliomarpm/udemy-downloader-gui#135]
### Description of the new feature / enhancement

By downloading courses at 1080p (in my specific case), I have an average speed of 10Mbps. Considering that I have a 1Gbps Fiber connection I think I should be able to download (I do it from other sites), at a much, much faster speed.
So the problem is with my line? of Udemy Servers? by Udeler?
A while ago I remember that I didn't have these speed problems. In practice, it takes forever to download 10GB of video, when generally I think 15 minutes would have been enough.

### Scenario when this would be used?

download

**Comment by Nickyg001** [comment]
I confirm that with the download video quality setting as Maximum (1080p), the download is very slow compared to the 720p setting. I have now tested it again.

as I wrote to you in another post. Then I saw that I had already reported this problem a long time ago.

**Comment by heliomarpm** [comment]
> I confirm that with the download video quality setting as Maximum (1080p), the download is very slow compared to the 720p setting. I have now tested it again.
> 
> as I wrote to you in another post. Then I saw that I had already reported this problem a long time ago.

I'm trying some ways to improve this

**Comment by heliomarpm** [comment]
New version available, check.
