### ISSUE TITLE
CAN't Download DRM videos :v is this something i should do ? 

### ISSUE THREAD

**Issue by UdelerFannumber1** [heliomarpm/udemy-downloader-gui#138]
### Udeler | Udemy Course Downloader

is the latest one

### Account Type?

Personal

### Steps to reproduce

it says DRM protected

### ✔️ Expected Behavior

cant download anything

### 🔍 Additional context

nope

**Comment by heliomarpm** [comment]
Udeler does not support DRM.  You would need a special key to break the encryption and you would also need another tool that supports this.

**Comment by heliomarpm** [comment]
You can try this.
https://github.com/Puyodead1/udemy-downloader

**Comment by tdn352001** [comment]
Hello sir, i can't find any guide to use this tool: https://github.com/Puyodead1/udemy-downloader, i haven't join owner record but i must be wait for three days. can you show me how to use this tool, please. Thanks.

**Comment by heliomarpm** [comment]
> Hello sir, i can't find any guide to use this tool: https://github.com/Puyodead1/udemy-downloader, i haven't join owner record but i must be wait for three days. can you show me how to use this tool, please. Thanks.

I am not the owner of this tool, but on the homepage there is all the information necessary for installation and use, but as I said you will still need a special key for each encrypted course
