### ISSUE TITLE
search_Error: ERR_BAD_REQUEST(403) Request failed with status code 403

### ISSUE THREAD

**Issue by djoudi** [heliomarpm/udemy-downloader-gui#141]
### Udeler | Udemy Course Downloader

1.12.7

### Account Type?

Personal

### Steps to reproduce

search_Error: ERR_BAD_REQUEST(403)
Request failed with status code 403

### ✔️ Expected Behavior

search_Error: ERR_BAD_REQUEST(403)
Request failed with status code 403

**Comment by heliomarpm** [comment]
Can you send me more information.
step by step to reproduce?
Logger tab information...

**Comment by heliomarpm** [comment]
closed due to lack of information
