### ISSUE TITLE
1080p download sound problems

### ISSUE THREAD

**Issue by ByNoNe** [heliomarpm/udemy-downloader-gui#146]
### Udeler | Udemy Course Downloader

1.12.7

### Account Type?

Business

### Steps to reproduce

When we want to download a 1080p video, the sound cuts out, is this problem only for me?

### ✔️ Expected Behavior

Fixing the intermittent sound when merging audio with video in 1080p video

### 🔍 Additional context

I had the same problem in MAC-Windows operating system

**Comment by heliomarpm** [comment]
> ### Udeler | Udemy Course Downloader
> 
> 1.12.7
> 
> ### Account Type?
> 
> Business
> 
> ### Steps to reproduce
> 
> When we want to download a 1080p video, the sound cuts out, is this problem only for me?
> 
> ### ✔️ Expected Behavior
> 
> Fixing the intermittent sound when merging audio with video in 1080p video
> 
> ### 🔍 Additional context
> 
> I had the same problem in MAC-Windows operating system

What's the course?

**Comment by heliomarpm** [comment]
closed, without enough information
