### ISSUE TITLE
DRM Protected

### ISSUE THREAD

**Issue by rolupin** [heliomarpm/udemy-downloader-gui#147]
### Udeler | Udemy Course Downloader

1.12.7

### Account Type?

Personal

### Steps to reproduce

when I try to download the videos I get the DRM Protected error.
I have tried with other versions where it appears that the problem is fixed but the error is the same,

### ✔️ Expected Behavior

I was hoping that with some version it could be fixed

**Comment by agarciagaray** [comment]
I have the same problem.

**Comment by Fdulcey19** [comment]
Tengo el mismo Problema

**Comment by heliomarpm** [comment]
Guys, unfortunately this is not a tool error, Udemy has been encrypting their courses for some time, making it impossible for Udeler to download them.  

The only known alternative is https://github.com/Puyodead1/udemy-downloader 

Good luck
