### ISSUE TITLE
Udemy Business No Course Found issue

### ISSUE THREAD

**Issue by maksen54** [heliomarpm/udemy-downloader-gui#148]
### Udeler | Udemy Course Downloader

1.12.7

### Account Type?

Business

### Steps to reproduce

l login in with acces token but my courses not shown in udeler 
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/141479903/ced177e5-8d47-4882-ae5b-b52a4061671b)

### ✔️ Expected Behavior

Will be great to downloand udemy business videos

**Comment by heliomarpm** [comment]
Make sure you entered your business subdomain correctly.  Make sure this user is enrolled in a course within the Udemy platform

**Comment by maksen54** [comment]
Hey,thank you very much, l just realze l did silly mistake and figure out after your correction
