### ISSUE TITLE
I stock in login page when I use Udeler

### ISSUE THREAD

**Issue by noamangg** [heliomarpm/udemy-downloader-gui#15]
I stock in login page when I use it when I press login it opens a new window then I login into my Udemy account but nothing happened
it opens like this
![Screenshot (177)](https://user-images.githubusercontent.com/71488276/148115526-9d783411-ba7a-41f0-b153-345f9328ad4a.png)

**Comment by noamangg** [comment]
![Screenshot (177)](https://user-images.githubusercontent.com/71488276/148114996-b45ed712-2fce-46c6-84ef-3f35ee7acb85.png)
 here the image i have faced

**Comment by heliomarpm** [comment]
Por favor verifique a última versão
