### ISSUE TITLE
Network issue

### ISSUE THREAD

**Issue by samascience** [heliomarpm/udemy-downloader-gui#150]
### Udeler | Udemy Course Downloader

1.12.7

### Account Type?

Business

### Steps to reproduce

when using a portal based token the issue is caused. 

### ✔️ Expected Behavior

network error

### 🔍 Additional context

8/29/2023, 3:11:36 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 3:11:35 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:55:12 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:59 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:58 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:58 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:58 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:58 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:58 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:58 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:58 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:58 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:58 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:58 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:58 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:58 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:58 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:58 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:57 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:56 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:55 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:54 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:53 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:52 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:51 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:50 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:49 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:48 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:47 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:46 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:46 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:46 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:46 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:46 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:46 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:46 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:46 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:46 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:46 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:46 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:46 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:46 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:46 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:45 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:44 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:44 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:44 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:44 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:44 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:44 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:44 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:44 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:44 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:44 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:44 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:44 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:44 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:44 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:43 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:43 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:43 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:43 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:43 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:43 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:43 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:43 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:43 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:43 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:43 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:43 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:43 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:42 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:42 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:42 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:42 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:41 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:41 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:41 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:39 PM - search_Error: ERR_NETWORK(0): Network Error
8/29/2023, 2:54:10 PM - search_Error: ERR_NETWORK(0): Network Error

**Comment by heliomarpm** [comment]
Were you able to connect, did you enter the subdomain of your business account?

**Comment by HackPoint** [comment]
> Were you able to connect, did you enter the subdomain of your business account?

I'm trying to but getting an empty white screen

**Comment by heliomarpm** [comment]
> > Were you able to connect, did you enter the subdomain of your business account?
> 
> I'm trying to but getting an empty white screen and it doesn't allows me to paste the access token into the input

Wow, it doesn't even show the login screen when you start the application?

**Comment by HackPoint** [comment]
> > > Were you able to connect, did you enter the subdomain of your business account?
> > 
> > 
> > I'm trying to but getting an empty white screen and it doesn't allows me to paste the access token into the input
> 
> Wow, it doesn't even show the login screen when you start the application?

Found why, after debugging it awhile, it was that I had been logged in, when started the application in dev mode , it started to work.

But I'm unable to use this application due to RDP rulles. IDK how to surpass them.

**Comment by heliomarpm** [comment]
I believe it is resolved in the latest version
