### ISSUE TITLE
DRM-Protection

### ISSUE THREAD

**Issue by Rapici** [heliomarpm/udemy-downloader-gui#151]
### Description of the new feature / enhancement

Hi Heliomar,
In first time, good job! Udeler it's amazing!
On an other hand, DRM-protect it's a first problem from udemy :( 
Are you and your team working for remove/jump DRM-protection? May be in future?
Many thanks a lot

Regards from Spain

### Scenario when this would be used?

Remove DRM-Protect

**Comment by LefterisRentas** [comment]
Any news about this?

**Comment by heliomarpm** [comment]
Folks, I have no plans to implement this in the future. Breaking the encryption requires a unique and distinct key for each user and encrypted course, several external tasks are necessary to obtain this key, which makes its implementation here at Udeler completely unfeasible.
Sorry..

**Comment by Rapici** [comment]
Hi @heliomarpm 
Ohhhhh bad news! :( 
No worries friend, you did a good job and amazing project with Udeler app and we hope in a future someone discover anything for breaking the encryption.

My best regards
Rapici

**Comment by heliomarpm** [comment]
> Thank you my friend.

**Comment by heliomarpm** [comment]
> Hi @heliomarpm Ohhhhh bad news! :( No worries friend, you did a good job and amazing project with Udeler app and we hope in a future someone discover anything for breaking the encryption.
> 
> My best regards Rapici

Thank you my friend.

**Comment by handi425** [comment]
> Folks, I have no plans to implement this in the future. Breaking the encryption requires a unique and distinct key for each user and encrypted course, several external tasks are necessary to obtain this key, which makes its implementation here at Udeler completely unfeasible. Sorry..

is there a form to place the key..?
so we can fill it in.

**Comment by heliomarpm** [comment]
> > Folks, I have no plans to implement this in the future. Breaking the encryption requires a unique and distinct key for each user and encrypted course, several external tasks are necessary to obtain this key, which makes its implementation here at Udeler completely unfeasible. Sorry..
> 
> is there a form to place the key..?
> so we can fill it in.

This possibility is still just an idea.  

You can try with https://github.com/Puyodead1/udemy-downloader

**Comment by Rapici** [comment]
Hi @heliomarpm 
well, I will try your option mentioned! 
Many thanks for the info

Regards!

**Comment by HackPoint** [comment]
> https://github.com/Puyodead1/udemy-downloader

Is it helped anyone?

**Comment by Rutvikballar** [comment]
> Folks, I have no plans to implement this in the future. Breaking the encryption requires a unique and distinct key for each user and encrypted course, several external tasks are necessary to obtain this key, which makes its implementation here at Udeler completely unfeasible. Sorry..



But Please Just Add supports of DRM protection For People Who have Decrption Keys of their own course so they can download easily any course they wants and own...

**Comment by Rutvikballar** [comment]
> > https://github.com/Puyodead1/udemy-downloader
> 
> Is it helped anyone?


Yes Buddy it's working and helped me a lot. you can also try if you have DRM Decryption keys.. it will work flowlessly

**Comment by Rutvikballar** [comment]
> https://github.com/Puyodead1/udemy-downloader

Would you add same feature as this ??  But with Excellent GUI like your own Udeler.... because i have used this. there is so much to do to run this

**Comment by Mikalodev** [comment]
Hello @all
Does the issue DRM protected fixed?

**Comment by Rutvikballar** [comment]
it's not issue!! it's protection that udemy added to so without DRM decrpter key and id of content .. you can download it.. it's illegal..  you need to obtained keys for specific coursed then after only then you can download any specific course from udemy..

**Comment by Mikalodev** [comment]
I normaly bought course but DRM protection content message appeared. I used the latest udeler version but coundt download the course

**Comment by Rutvikballar** [comment]
> I normaly bought course but DRM protection content message appeared. I used the latest udeler version but coundt download the course

if you have bought the course on your own money. then and only then i will help..

**Comment by Mikalodev** [comment]
Have you got the latest version that bypass it?

**Comment by Rutvikballar** [comment]
use this https://github.com/Puyodead1/udemy-downloader

> Have you got the latest version that bypass it?

there is not any bypass trick you need DRM decrption keys for specific course which you are planning to download..

https://github.com/Puyodead1/udemy-downloader

**Comment by Mikalodev** [comment]
> > I normaly bought course but DRM protection content message appeared. I used the latest udeler version but coundt download the course
> 
> if you have bought the course on your own money. then and only then i will help..

Have u got telegram account I want to know further about the course I bought and I couldnt download it

**Comment by Rutvikballar** [comment]
> > > I normaly bought course but DRM protection content message appeared. I used the latest udeler version but coundt download the course
> > 
> > 
> > if you have bought the course on your own money. then and only then i will help..
> 
> Have u got telegram account I want to know further about the course I bought and I couldnt download it

https://t.me/itzz_RB

**Comment by franitpro** [comment]
Most of the courses in udeler v1.3.2 has started giving the "Video with DRM Protection" error log.
Its now just becoming annoying and disappointing..
Cant do anything now with Udeler..  :(

**Comment by heliomarpm** [comment]
> Most of the courses in udeler v1.3.2 has started giving the "Video with DRM Protection" error log.
> Its now just becoming annoying and disappointing..
> Cant do anything now with Udeler..  :(

I share your feeling.

**Comment by Nickyg001** [comment]
@heliomarpm  
I just discovered and tried version 1.13.3!
- With Free Udemi Courses the download starts regularly.
- With Courses that are not free but present in my account therefore regularly paid, there is always the DRM problem even with the Token inserted.

Am I doing something wrong or is the problem not yet definitively resolved?

**Comment by heliomarpm** [comment]
> @heliomarpm I just discovered and tried version 1.13.3!
> 
> * With Free Udemi Courses the download starts regularly.
> * With Courses that are not free but present in my account therefore regularly paid, there is always the DRM problem even with the Token inserted.
> 
> Am I doing something wrong or is the problem not yet definitively resolved?

https://github.com/heliomarpm/udemy-downloader-gui/issues/151#issuecomment-2314976886

**Comment by zakimimit** [comment]
The same problem

**Comment by heliomarpm** [comment]
> > > @heliomarpm I just discovered and tried version 1.13.3!
> > > 
> > > * With Free Udemi Courses the download starts regularly.
> > > * With Courses that are not free but present in my account therefore regularly paid, there is always the DRM problem even with the Token inserted.
> > > 
> > > Am I doing something wrong or is the problem not yet definitively resolved?
> > 
> > 
> > [#151 (comment)](https://github.com/heliomarpm/udemy-downloader-gui/issues/151#issuecomment-2314976886)
> 
> I don't understand, do I have to use another script outside of Udler? So what is the Udler Access Token for if it doesn't download "my" purchased courses? So how does this script work?

Udeler is used to download all the content of your purchased courses and release them for download in a simple and organized way. If the course is protected, consequently the video lessons will be blocked for download, but you can still download the attachments.

If you have the knowledge and willingness to violate copyright laws, you can try the other way.
