### ISSUE TITLE
1080p image is downloaded as 720p.

### ISSUE THREAD

**Issue by Canmemis** [heliomarpm/udemy-downloader-gui#159]
### Udeler | Udemy Course Downloader

1.12.7

### Account Type?

Personal

### Steps to reproduce

Hello,

Currently, when I want to download from Udeler, it downloads as 720p even though the video quality is 1080p.
https://github.com/heliomarpm/udemy-downloader-gui/releases
I am using the 64 bit version available here.
in the settings I selected the option to download in highest resolution. but it downloads in 720p.
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/88040387/4e685631-d767-4c23-b444-0cc71ae28b79)
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/88040387/8d312453-dada-4255-987d-cc3b41c62941)

training normally supports 1080p.
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/88040387/304a3036-f458-405e-aa0c-d372b17e253b)

https://www.udemy.com/course/python-baslangictan-ileri-seviye-yazilim-dersleri/learn/lecture/23587198#questions

### ✔️ Expected Behavior

Make it download videos in 1080p files as 1080p.

### 🔍 Additional context

Windows 11

**Comment by Canmemis** [comment]
Is the problem solved? I don't quite understand.

**Comment by heliomarpm** [comment]
> Is the problem solved? I don't quite understand.

In the courses I have access to, I was able to download in 1080p without any problems.
Did you save the information in the settings tab before starting the download?

**Comment by feriishere** [comment]
yeah there is no 1080p in the list, but works amazing. i guess the originial one supports 1080p but for some reason this repo is much better

**Comment by heliomarpm** [comment]
New version available, check.
