### ISSUE TITLE
New Bug - Stuck on Building Course Data

### ISSUE THREAD

**Issue by Cm13my** [heliomarpm/udemy-downloader-gui#16]
Stuck on Building Course Data
Tried VPN
Proxy, socks 5
Changed PC hwid
tried everything

also deleted cookies, etc, still not working
tried changing account

Please Help

**Comment by heliomarpm** [comment]
Tried with the latest version 1.10.3?

**Comment by MarcVCE** [comment]
Yes

**Comment by contracode** [comment]
Confirming the same issue and fix that @joejordan posted. Thank you, @joejordan!

**Comment by heliomarpm** [comment]
Please let me know which course you have with this problem

**Comment by contracode** [comment]
@heliomarpm "NATRON The FREE robust alternative to NUKE & AFTER EFFECTS" had this issue.

**Comment by heliomarpm** [comment]
Duplicate of #12
