### ISSUE TITLE
Stuck download course

### ISSUE THREAD

**Issue by HelloWorldDC** [heliomarpm/udemy-downloader-gui#168]
### Udeler | Udemy Course Downloader

1.12.7

### Account Type?

Business

### Steps to reproduce

I got an error while trying to download the [Android App Hacking - Black Belt Edition](https://www.udemy.com/course/android-app-hacking-black-belt-edition/) course, I only changed the download settings to best quality and change archive folder, everything else I left as default. After downloading a specific item, for example in the image below, I got an error when downloading the 84th item. I waited patiently for 30 minutes but still nothing happened. I tried download again but when I got to the 84th item it was still stuck. I checked Logger but nothing logged. I thought it was due to a network problem, but I tried downloading another course and the download process was completely normal.

![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/79351507/4507586c-a368-4b99-afb3-36e25f28e957)

### ✔️ Expected Behavior

The course is downloaded normally.

### 🔍 Additional context

I used the software on Windows Server 2022 Standard 64-bit, version	21H2, OS build 20348.1970.

**Comment by heliomarpm** [comment]
Please check and send me the error described in the Logger tab.

Most of the videos in this course are encrypted and cannot be downloaded with Udeler.

In the settings there is an option to download all attachments and videos released from the course, this option is only used to not interrupt the download in cases of encrypted video.

**Comment by HelloWorldDC** [comment]
@heliomarpm I checked Logger tab but nothing logged. I tried checking in task manager and found it was full memory. I took a video to record it

https://github.com/heliomarpm/udemy-downloader-gui/assets/79351507/b7245473-dfcb-4206-8c06-d2a809f8a2ff

**Comment by heliomarpm** [comment]
New version available, check.
