### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by parvinders347** [heliomarpm/udemy-downloader-gui#169]
### Udeler | Udemy Course Downloader

1.12.7

### Account Type?

Subscriber

### Steps to reproduce

After Starting the udeler it shows "(node:3200) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead."

I think that is why my course downloading speed is slow(5kbps speed) because I'm using 10mbps internet.

### ✔️ Expected Behavior

I don't know where to change the code I think this article help you regarding this topic: [https://bobbyhadz.com/blog/deprecation-warning-buffer-is-deprecated-due-to-security-and-usability-issues](url)

Please can you solve the issue?
Thanks.

**Comment by heliomarpm** [comment]
resolved in latest version
