### ISSUE TITLE
Udeler Error Download

### ISSUE THREAD

**Issue by HeshamAlads** [heliomarpm/udemy-downloader-gui#181]
### Udeler | Udemy Course Downloader

1.12.7

### Account Type?

Personal

### Steps to reproduce

<img width="984" alt="udeler3" src="https://github.com/heliomarpm/udemy-downloader-gui/assets/38578228/4454cdcb-3579-4fcb-877f-e874afdd3cf3">

### ✔️ Expected Behavior

i think this extension >> .mp4.mtd >> 1. Intro to course.mp4.mtd

errorDownload
The .mtd file is corrupt. Start a new download.

errorDownload
Invalid file path: D:\Udemy\Udemy Courses/Mastering Flutter Responsive/1. Introduction/1. Intro to course.mp4.mtd

**Comment by heliomarpm** [comment]
This is a common error, to resolve, close the application and before opening it again, check if the file still exists and delete it manually
