### ISSUE TITLE
Download Error .MTD file corrupt 

### ISSUE THREAD

**Issue by user3425f** [heliomarpm/udemy-downloader-gui#182]
### Udeler | Udemy Course Downloader

Udeler v1.12.7

### Account Type?

Personal

### Steps to reproduce

"The .mtd file is corrupt. Start a new download." error in logs.

### ✔️ Expected Behavior

.

**Comment by heliomarpm** [comment]
Hello.
This is a common error, to resolve, close the application and before opening it again, check if the file still exists and delete it manually

**Comment by user3425f** [comment]
Thank you for the answer. There is one more problem. Even though I have a subscription, the "change search mode" option does not appear. I want to download the courses included in my subscription, but I cannot see them.

**Comment by heliomarpm** [comment]
> Thank you for the answer. There is one more problem. Even though I have a subscription, the "change search mode" option does not appear. I want to download the courses included in my subscription, but I cannot see them.

this is a complicated problem to solve, to figure out this signature problem the user had to share the access token with me.  If you can open an issue with a little more detail, I can try to resolve it.

Sorry for my english.

**Comment by futuregate2016** [comment]
Just set download quality to Highest 1080 and it will download without any problem
