### ISSUE TITLE
certificate has expired at TLSSocket

### ISSUE THREAD

**Issue by SKGaminG28** [heliomarpm/udemy-downloader-gui#183]
### Udeler | Udemy Course Downloader

1.12.7

### Account Type?

Personal

### Steps to reproduce

While Click on download.
Error: certificate has expired at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34) at TLSSocket.emit (events.js:315:20) at TLSSocket._finishInit (_tls_wrap.js:936:8) at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/66673450/5f631075-944a-4414-921a-e885bc85a5c0)

### ✔️ Expected Behavior

Download should be started

**Comment by SKGaminG28** [comment]
any update??

**Comment by heliomarpm** [comment]
> any update??

Sorry friend, you can't reproduce this error, perhaps because you are already using a version with dependent library updates.
I will soon make a new version available and you can test it again.
