### ISSUE TITLE
downloadChapter_Error

### ISSUE THREAD

**Issue by futuregate2016** [heliomarpm/udemy-downloader-gui#185]
### Udeler | Udemy Course Downloader

1.12.8

### Account Type?

Personal

### Steps to reproduce

![Capture](https://github.com/heliomarpm/udemy-downloader-gui/assets/168378848/84acae2b-fc22-45eb-9b7a-ba0ebdcc626c)

### ✔️ Expected Behavior

Hi, on the new updated version , i got this error when i try to download any course
downloadChapter_Error:
mkdirp is not a function

### 🔍 Additional context

OS : Windows 10 64bit

**Comment by heliomarpm** [comment]
thanks @futuregate2016

**Comment by eslamlotfy213** [comment]
when  make donwload from business videos not work ?

**Comment by heliomarpm** [comment]
> when make donwload from business videos not work ?

Are you using the latest version?
What is the error exactly?
