### ISSUE TITLE
I can't log in. When I put my credentials I go to the site and it is not possible to download

### ISSUE THREAD

**Issue by joaovrmdev** [heliomarpm/udemy-downloader-gui#19]
![image](https://user-images.githubusercontent.com/83680277/151373512-79feda9f-842f-4265-981b-7bb7f7b7dfce.png)

I can't get out of it, I've already downloaded all the official versions basically, can anyone help please?

**Comment by heliomarpm** [comment]
which version are you using? Udemy has modified the login system, this tweak is available from version 1.10.2.
