### ISSUE TITLE
Udeler_Setup-v1.12.9_mac-arm64.dmg not working on MacOS Sonoma (Apple Silicon)

### ISSUE THREAD

**Issue by urquiaernesto** [heliomarpm/udemy-downloader-gui#190]
### Udeler | Udemy Course Downloader

1.12.9

### Account Type?

Personal

### Steps to reproduce

Steps to reproduce:

- Download Udeler_Setup-v1.12.9_mac-arm64.dmg
- Attempt to open the file
- MacOS indicates the file is damaged and moves it to the Trash

### ✔️ Expected Behavior

The application should open and function correctly without indicating that the file is damaged.

### 🔍 Additional context

OS: MacOS Sonoma
Processor: Apple Silicon

Note: I had to install a previous version (Udeler_Setup-v1.12.7_mac-x64.dmg) which worked fine.

**Comment by heliomarpm** [comment]
Hello, the installation works fine and the application does not open? Or installation didn't work?

**Comment by urquiaernesto** [comment]
Hello,

The installation process itself works fine: I can open the DMG file, drag the app to the Applications folder, and that completes without any issues. However, when I try to open the application, I receive an error indicating that the file is damaged and it is moved to the Trash.

t seems likely that there is a problem with the new "Universal" version compiled for the first time. The Udeler_Setup-v1.12.7_mac-x64.dmg version for Intel processors works, but the new version Udeler_Setup-v1.12.9_mac-arm64.dmg for Apple Silicon does not.

**Comment by ahmed1234ahmed** [comment]
same issue in both .zip and dmg, using Mackbook M3

**Comment by heliomarpm** [comment]
> Solução alternativa (no meu M1 Sonoma 14.5):
> 
> ```
> xattr -c /Applications/Udeler.app 
> ```
> 
> Então eu posso executar o aplicativo Udeler sem personalizar "Segurança do sistema / privacidade".
> 
> Btw, em outra máquina (Mac Intel), eu só posso executar 1.12.7 porque há apenas a versão 1.12.9 para "arm64". Gostaria de saber por que não há lançamento "Mac_x64" para 1.12.9?

There was a failure in publishing this, a new one will be released in a few days

**Comment by heliomarpm** [comment]
New version available, check.

**Comment by calves07** [comment]
Same problem. The workaround mentioned above worked fine tho.
