### ISSUE TITLE
Request failed with status code 403

### ISSUE THREAD

**Issue by ahmed1234ahmed** [heliomarpm/udemy-downloader-gui#191]
### Udeler | Udemy Course Downloader

1.12.7 Mac version

### Account Type?

Personal

### Steps to reproduce

6/27/2024, 12:05:41 AM - search_Error: ERR_BAD_REQUEST(403): Request failed with status code 403

### ✔️ Expected Behavior

this error while open udeler
Request failed with status code 403

### 🔍 Additional context

MacOS

**Comment by heliomarpm** [comment]
New version available, check.
