### ISSUE TITLE
Course download error

### ISSUE THREAD

**Issue by wbeimaro** [heliomarpm/udemy-downloader-gui#193]
### Udeler | Udemy Course Downloader

1.12.9

### Account Type?

Personal

### Steps to reproduce

I started the download of the course and when it was at 57% it stopped, in the view menu I gave it to force reload and I had to restart it and it started and as it checked that the previous files were already there and reached 57% again, and the same thing happened again it stopped there and did not continue the download, as well as the buttons that allow to download, stop or continue the download are disabled.

In the logger the following types of messages are displayed:

1. getLecture_Error: ERR_BAD_RESPONSE(520)
Request failed with status code 520
2. getLectureAndAttachments_Error: ERR_BAD_RESPONSE(520)
Request failed with status code 520
3. getLecture_Error: ERR_BAD_RESPONSE(503)
Request failed with status code 503
4. getLectureAndAttachments_Error: ERR_BAD_RESPONSE(503)
Request failed with status code 503
5. getLecture_Error: ECONNABORTED(0)
timeout of 40000ms exceeded
6. getLectureAndAttachments_Error: ECONNABORTED(0)
timeout of 40000ms exceeded

Attachments

![Captura de pantalla 2024-07-02 145712](https://github.com/heliomarpm/udemy-downloader-gui/assets/171868107/611750b0-199b-47ee-ad7b-1da0abf74809)
![image](https://github.com/heliomarpm/udemy-downloader-gui/assets/171868107/3b3bac63-e177-4282-8019-da7bdba26f75)
[udeler_logger.txt](https://github.com/user-attachments/files/16074978/udeler_logger.txt)

### ✔️ Expected Behavior

That I could download the whole course without any problem.

### 🔍 Additional context

Windows 11

**Comment by heliomarpm** [comment]
A new version that reduces access to the Udemy API is in the final stages of development, and should resolve this problem

**Comment by heliomarpm** [comment]
New version available, check.
