### ISSUE TITLE
No courses found

### ISSUE THREAD

**Issue by santhoshn24** [heliomarpm/udemy-downloader-gui#197]
### Udeler | Udemy Course Downloader

1.13.0

### Account Type?

Business

### Steps to reproduce

1 ) When logged in through the access token, I was successfully logged in but there were no courses that i have enrolled to download
2) I read one of the issues where you said  "first you need to activate the business option, fill in the subdomain and then enter the token" https://github.com/heliomarpm/udemy-downloader-gui/issues/134#issuecomment-1603306255, I did that but I see an error now rather than logging in which says
```
.:: AxiosError ::.
Network Error
```

![image](https://github.com/user-attachments/assets/f9fab233-d231-43c7-8e95-942aab0ddcc4)

### ✔️ Expected Behavior

Will be great to downloand udemy business videos

### 🔍 Additional context

Trying to download the courses from a business account

**Comment by heliomarpm** [comment]
I no longer have a business account to test this, but testing with my personal account I can connect using token normally.

If you can send me your token and subdomain in your personal email, I can quickly identify what may be happening.
Please let me know if you decide to send me the information here, so I can check my emails.

**Comment by santhoshn24** [comment]
Sorry

**Comment by heliomarpm** [comment]
> @heliomarpm i have also same issue no course found in personal plan subscription account.
> i sent you email also kindly check and help if you want token i can help you to give it.

Mr. Vick?

**Comment by heliomarpm** [comment]
check the new version, please

**Comment by santhoshn24** [comment]
> check the new version, please

Hi @heliomarpm, I just tried the latest version and I was able to login and see all the courses that I have been enrolled but upon clicking download, I get 

```
Download Failed
Click to retry
```

Screenshots and log below,
![image](https://github.com/user-attachments/assets/cc904e67-4c2e-4660-872f-d34aadc1e29b)
![image](https://github.com/user-attachments/assets/726a9603-cbe4-4d3d-b952-aaecf40ff5be)

![image](https://github.com/user-attachments/assets/1194c428-1312-482f-824a-22215489ab95)

**Comment by heliomarpm** [comment]
Hi @santhoshn24 
I solved a problem like this in version 1.13.1. I'll see if I have any more courses in my account to test. 

I lost my access to the business account, so it's difficult to find and fix these problems.

**Comment by santhoshn24** [comment]
@heliomarpm thanks and let me know next time if you get this to work, Appreciate your efforts, Many Thanks.

**Comment by heliomarpm** [comment]
see a new version

**Comment by santhoshn24** [comment]
@heliomarpm Thanks again, the downloading tries to start but the ones that I need are DRM protected, so doesnt go through.
`Contains DRM protection and cannot be downloaded
Click to dismiss`

Are all videos on Udemy DRM protected?

**Comment by heliomarpm** [comment]
> @heliomarpm Thanks again, the downloading tries to start but the ones that I need are DRM protected, so doesnt go through. `Contains DRM protection and cannot be downloaded Click to dismiss`
> 
> Are all videos on Udemy DRM protected?

Hi @santhoshn24, unfortunately many are protected, but fortunately some are still possible to download in full.

You can try with https://github.com/Puyodead1/udemy-downloader
