### ISSUE TITLE
EPREPARE_DOWNLOADING: (0) Cannot read property 'asset_type' of undefined EBUILDING_COURSE_DATA: undefined(0) Cannot read property 'asset_type' of undefined

### ISSUE THREAD

**Issue by Manfrad** [heliomarpm/udemy-downloader-gui#198]
### Udeler | Udemy Course Downloader

1.13.0

### Account Type?

Personal

### Steps to reproduce

When trying to download SRT files,
the job takes a long time with the information "Building Course Data"
then throws these error information consistently

EPREPARE_DOWNLOADING: (0)
Cannot read property 'asset_type' of undefined

EBUILDING_COURSE_DATA: undefined(0)
Cannot read property 'asset_type' of undefined

### ✔️ Expected Behavior

Downloading resources of the course.

### 🔍 Additional context

Windows 11

**Comment by heliomarpm** [comment]
what's name of the course?

**Comment by Manfrad** [comment]
Hi

Thank you for your reply.

The course is
Professional Intelligence Analyst
