### ISSUE TITLE
lecture.quality.toLowerCase is not a function

### ISSUE THREAD

**Issue by przemekzst** [heliomarpm/udemy-downloader-gui#201]
### Udeler | Udemy Course Downloader

v1.13.0

### Account Type?

Personal

### Steps to reproduce

When clicked download icon i get errors:
26.07.2024, 07:17:16 - EPREPARE_DOWNLOADING: (0): lecture.quality.toLowerCase is not a function
26.07.2024, 07:17:16 - EBUILDING_COURSE_DATA: undefined(0): lecture.quality.toLowerCase is not a function

### ✔️ Expected Behavior

courses start downloading

**Comment by przemekzst** [comment]
![image](https://github.com/user-attachments/assets/48701362-0dc1-4a1d-a4a4-9fcd4f9fab9b)
![image](https://github.com/user-attachments/assets/81d17b13-e97b-4f16-9963-0521ee652be5)

**Comment by redFox22** [comment]
On version 1.13.1 I keep getting this error.

**Comment by heliomarpm** [comment]
see a new version

**Comment by rattyrat8682** [comment]
1.13.2 still has this issue.

**Comment by heliomarpm** [comment]
> 1.13.2 still has this issue.

Hi, send a screenshot of session logger and course name

**Comment by SalimElheni1** [comment]
Hey
Version 1.13.2 still has the same issue
![image](https://github.com/user-attachments/assets/0b6c6e1e-c31f-45b3-8916-a96a22061b4b)

**Comment by YASHDEV42** [comment]
> Hey Version 1.13.2 still has the same issue ![image](https://private-user-images.githubusercontent.com/16426020/364147960-0b6c6e1e-c31f-45b3-8916-a96a22061b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDIxOTUsIm5iZiI6MTcyNjUwMTg5NSwicGF0aCI6Ii8xNjQyNjAyMC8zNjQxNDc5NjAtMGI2YzZlMWUtYzMxZi00NWIzLTg5MTYtYTk2YTIyMDYxYjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE1NTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYTdiZjE1MjAwZDRkNjliN2QyNjY3YmI3YmFmNTk2ZWYxNGIxZTg0Mjc3MWM1MmQ5YzE5NTk3MGMzYTliMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZUa20g06zZVzrPFfrhrgNdo2Em5aF6Bu06XE1ulOlak)

try changing the video quality to highest like this :
![Screenshot 2024-09-16 185210](https://github.com/user-attachments/assets/176fadb6-19de-44ea-b60e-efcd98c9ff77)

**Comment by magowiz** [comment]
I'm using 1.13.3 and I get same issues even setting quality to to highest, and no video gets downloaded at all.
