### ISSUE TITLE
Application login page crashed

### ISSUE THREAD

**Issue by mehmet-ercan** [heliomarpm/udemy-downloader-gui#203]
### Udeler | Udemy Course Downloader

1.8.1

### Account Type?

Personal

### Steps to reproduce

Hello, I downloaded the repo and ran the npm install command.
Then I ran the npm start command and got the following error.
and the application looks like this.

![image](https://github.com/user-attachments/assets/9e9535a6-becc-4131-bd2b-d6bae4d3cd95)
![image](https://github.com/user-attachments/assets/87647c28-f3e1-4698-9163-922542cd70ba)

### ✔️ Expected Behavior

Application login screens should appear.

### 🔍 Additional context

OS: Linux Mint 21.3

**Comment by heliomarpm** [comment]
run "npm run dev", this will allow you to debug the code
