### ISSUE TITLE
Neither rof my two courses are downloading. Receiving error status code 503.

### ISSUE THREAD

**Issue by tedtninety** [heliomarpm/udemy-downloader-gui#204]
### Udeler | Udemy Course Downloader

1.13

### Account Type?

Personal

### Steps to reproduce

1. I login to my account via UCD 1.13
2. Select one or either of my 2 paid courses to download
3. It remains on 0% -Building Course Data
4. Logger outputs Errors ( please see screenshot )

### ✔️ Expected Behavior

Able to download my courses so that I may view them offline on my treadmill.
![efew87](https://github.com/user-attachments/assets/0d60be99-d0b2-4b56-9781-746b30797bb4)

### 🔍 Additional context

Thanks in advance.

**Comment by viveksvdy2014** [comment]
I am also facing the same issue.

**Comment by tedtninety** [comment]
Hi @heliomarpm why did you mark this as complete?

**Comment by heliomarpm** [comment]
> Hi @heliomarpm why did you mark this as complete?

Hi. 
A new version is available

**Comment by viveksvdy2014** [comment]
Hi @heliomarpm
I tried downloading some of the courses I own a couple of times after pulling the latest code but I am still receiving the same error code.
![image](https://github.com/user-attachments/assets/86286857-a038-4a19-9bbf-82d3cff75ae5)
![image](https://github.com/user-attachments/assets/84724d5d-e5c0-4936-9894-04e3ef10c94f)
![image](https://github.com/user-attachments/assets/462c7f67-8a6b-4e9c-ba67-de2f11185aad)

**Comment by tedtninety** [comment]
> > Hi @heliomarpm why did you mark this as complete?
> 
> Hi. A new version is available

Oh I didn't know thank you!

**Comment by heliomarpm** [comment]
> > > Hi @heliomarpm why did you mark this as complete?
> > 
> > 
> > Hi. A new version is available
> 
> Oh I didn't know thank you!

Hi @tedtninety.
This is actually an error in Udemy API.
Please try to log in with a new token, please let me know the result.

**Comment by viveksvdy2014** [comment]
Tried re-logging in, first using credentials in the app itself, then using auth_token. Issue persisted both times.
log:
8/21/2024, 6:12:25 AM - EPREPARE_DOWNLOADING: ERR_BAD_RESPONSE(503): Service is temporarily unavailable. Please wait a few minutes and try again.
8/21/2024, 6:12:24 AM - EBUILDING_COURSE_DATA: ERR_BAD_RESPONSE(503): Service is temporarily unavailable. Please wait a few minutes and try again.

 course: Java 17 Masterclass: Start Coding in 2024

**Comment by viveksvdy2014** [comment]
Looks like this issue is only occurring with certain courses in my catalogue. I tried downloading all courses and it failed for 9 out of 27 course (Some of the ones which did not fail had DRM, but since that's something we can't do anything about, I am ignoring).

**Comment by tedtninety** [comment]
Hi @heliomarpm I was excited! However, I just tried the new version and it was like before.  It stays stuck on Building course data.
![image](https://github.com/user-attachments/assets/1b5aeaaf-84bd-41f7-9653-328980a92890)

**Comment by heliomarpm** [comment]
> Hi @heliomarpm I was excited! However, I just tried the new version and it was like before.  It stays stuck on Building course data.
> ![image](https://github.com/user-attachments/assets/1b5aeaaf-84bd-41f7-9653-328980a92890)
> 
This screenshot is from a very old version, the current version is 1.13

**Comment by tedtninety** [comment]
Hi @heliomarpm .Apologies. May I please trouble you for the link to the installer?
Thank you again for your brilliant work.

**Comment by heliomarpm** [comment]
> Oi . Desculpas. Posso incomodá-lo para o link para o instalador? Obrigado novamente por seu brilhante trabalho.



> Hi @heliomarpm .Apologies. May I please trouble you for the link to the installer? Thank you again for your brilliant work.


https://github.com/heliomarpm/udemy-downloader-gui/releases

**Comment by heliomarpm** [comment]
> Hi @heliomarpm , Thank you. Unfortunately it is not working. ![ud1](https://private-user-images.githubusercontent.com/115969035/361513268-c3a9efaf-2031-41f5-9ec0-261344f19403.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NzA0OTYsIm5iZiI6MTcyNDk3MDE5NiwicGF0aCI6Ii8xMTU5NjkwMzUvMzYxNTEzMjY4LWMzYTllZmFmLTIwMzEtNDFmNS05ZWMwLTI2MTM0NGYxOTQwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQyMjIzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTJmN2NjNmZkZWRkZjk2ZmE4YWEwZTg1YTdkYTM2YTNjYmM0ZTYzNjUyZmIwNzM3NTkzNzc2Zjk0ODJkMTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bgC6NGpTRSOeE8ZQ8A9XdSnYLd1JVbO_56KtS1LV3Os)
> 
> I waited a few minutes and tried again, and still hasn't worked. If it helps, I certainly purchased these courses.

This error is under investigation, apparently it is a problem related only to some courses.

PS. This software only allows you to download courses that you have already purchased, except for DRM-protected courses. OK

**Comment by tedtninety** [comment]
HI @heliomarpm . Yes indeed. I paid for both  courses. I await your solution,. Thank you again.

**Comment by heliomarpm** [comment]
see a new version

**Comment by tedtninety** [comment]
Thank you @heliomarpm ! This time it worked for one of them, thank you. The other is DRM. Will there be a workaround for that at all if I may asl?
Thank you again for your brilliant work!

**Comment by heliomarpm** [comment]
> Thank you @heliomarpm ! This time it worked for one of them, thank you. The other is DRM. Will there be a workaround for that at all if I may ask?
> Thank you again for your brilliant work!

You can try with https://github.com/Puyodead1/udemy-downloader

**Comment by tedtninety** [comment]
Thanks again! Really appreciate you!
Would you know of he has an exe as well. I am not as savvied a coder.
Thank you.

**Comment by heliomarpm** [comment]
> Thanks again! Really appreciate you!
> Would you know of he has an exe as well. I am not as savvied a coder.
> Thank you.

I don't know, the code is python and has clear instructions on how to run it
