### ISSUE TITLE
I can't download a course.

### ISSUE THREAD

**Issue by karamizrak** [heliomarpm/udemy-downloader-gui#206]
### Udeler | Udemy Course Downloader

1.13.0

### Account Type?

Personal

### Steps to reproduce

![2024-08-16_103526](https://github.com/user-attachments/assets/cc1a4df9-b51e-4069-9ed2-469a88ff1ed4)

EBUILDING_COURSE_DATA: undefined(0)
Cannot read property 'asset_type' of undefined

### ✔️ Expected Behavior

I want to be able to download this like my other courses :)

### 🔍 Additional context

Operating System: windows 10

**Comment by heliomarpm** [comment]
Hi, which course?

**Comment by karamizrak** [comment]
https://www.udemy.com/course/sfrdan-ileri-seviye-angular-egitimi

> Hi, which course?

**Comment by heliomarpm** [comment]
> https://www.udemy.com/course/sfrdan-ileri-seviye-angular-egitimi
> 
> > Hi, which course?

This is actually an error in Udemy API.
Please try to log in with a new token, please let me know the result.

**Comment by heliomarpm** [comment]
see a new version
