### ISSUE TITLE
Contain DRM Protection and cannot be downloaded

### ISSUE THREAD

**Issue by rhodfem** [heliomarpm/udemy-downloader-gui#210]
### Udeler | Udemy Course Downloader

v1.12.9, v1.13.0, v1.13.1

### Account Type?

Business

### Steps to reproduce

![WhatsApp Image 2024-08-21 at 00 16 12](https://github.com/user-attachments/assets/bb12a8fc-8c67-49b8-bf2c-b05961530f6b)
![WhatsApp Image 2024-08-21 at 00 16 11](https://github.com/user-attachments/assets/6ee74dc9-7601-4854-8642-d9964ed97bde)

### ✔️ Expected Behavior

I should be able to successfully download the udemy files
<img width="766" alt="v1 13 1" src="https://github.com/user-attachments/assets/f0bb3971-232b-4746-aa69-4cbdc1cb8c4c">

### 🔍 Additional context

os: win11 x64

**Comment by heliomarpm** [comment]
Hi @rhodfem, 
These courses are encrypted and cannot be downloaded.
