### ISSUE TITLE
1.13.1 not workin MacOS M3 

### ISSUE THREAD

**Issue by ahmed1234ahmed** [heliomarpm/udemy-downloader-gui#211]
### Provide a description of requested docs changes

after installation, not work , MAC M3 ( sonoma 14.6.1 ) 
<img width="382" alt="Screenshot 2024-08-22 at 14 21 13" src="https://github.com/user-attachments/assets/d24cc275-22bf-4acd-bb1e-f2ee4f32a8d5">

**Comment by heliomarpm** [comment]
I really have no way of figuring out the problem as I don't have MacOS, we'll have to wait for someone else to contribute to this. Oh, some reports that version 1.12.7 still works on MacOS, you can try it.

**Comment by erzhan89** [comment]
@ahmed1234ahmed,
in Terminal: 
 xattr -c /Applications/Udeler.app

**Comment by heliomarpm** [comment]
[Comment on the duplicate issue:
This issue is being merged with [issue #199](https://github.com/heliomarpm/udemy-downloader-gui/issues/199). Please follow the progress there.](url)
