### ISSUE TITLE
lecture.quality.toLowerCase is not a function

### ISSUE THREAD

**Issue by redFox22** [heliomarpm/udemy-downloader-gui#212]
### Udeler | Udemy Course Downloader

1.13.1

### Account Type?

Personal

### Steps to reproduce

When I click on any download icon for any course:

EPREPARE_DOWNLOADING: (0): lecture.quality.toLowerCase is not a function
EBUILDING_COURSE_DATA: (0): lecture.quality.toLowerCase is not a function

### ✔️ Expected Behavior

Downloading course

### 🔍 Additional context

I have tried logging off and using both authentications (access token and login) but it doesn't work.
OS: Windows 11

**Comment by heliomarpm** [comment]
see a new version
