### ISSUE TITLE
Courses from the personal plan are not downloaded

### ISSUE THREAD

**Issue by nullablege** [heliomarpm/udemy-downloader-gui#213]
### Udeler | Udemy Course Downloader

1.13.2

### Account Type?

Personal

### Steps to reproduce

It used to be that a notification would pop up at the top and after you pressed it, it would become available for download. But that doesn't happen anymore. By the way, I had another course other than the personal plan, could it be because of this? 

### ✔️ Expected Behavior

It used to be that a notification would pop up at the top and after you pressed it, it would become available for download. But that doesn't happen anymore. By the way, I had another course other than the personal plan, could it be because of this?

**Comment by heliomarpm** [comment]
This notification still exists and will always appear if no course is found!
When connecting, is any course from the personal account displayed?

**Comment by heliomarpm** [comment]
fixed in new version 1.13.3
