### ISSUE TITLE
Specified Download Rage (Download Start .. Download End ...) throws error

### ISSUE THREAD

**Issue by Manfrad** [heliomarpm/udemy-downloader-gui#222]
### Udeler | Udemy Course Downloader

v1.13.3

### Account Type?

Personal

### Steps to reproduce

If I configure a specified starting and end range, a blue bar runs for a few seconds. Then it states "EASK_FOR_SUBTITLE: (0) downloadStart is not defined" and stops the download.

### ✔️ Expected Behavior

Program is stable.
Download is not started in a controlled manner.

**Comment by heliomarpm** [comment]
Try save new settings

**Comment by heliomarpm** [comment]
> No change.
> Set to 20 as start unit, fails.
> Set to 1 as start unit, fails
> Disable "Enable Download Start/End", everything OK.

Send me prints, logs and course name

**Comment by Manfrad** [comment]
Hi there

Thanks for your response, please find attached the information requested.

I hope prints mean screen shots, otherwise pls let me know.
