### ISSUE TITLE
EPREPARE_DOWNLOADING: (0) lecture.quality.slice is not a function

### ISSUE THREAD

**Issue by geobruce** [heliomarpm/udemy-downloader-gui#226]
### Udeler | Udemy Course Downloader

V1.13.4

### Account Type?

Business

### Steps to reproduce

For every course that I try to download I get the following error in the log:

EPREPARE_DOWNLOADING: (0)
lecture.quality.slice is not a function
course: The Complete 2024 Web Development Bootcamp
EBUILDING_COURSE_DATA: (0)
lecture.quality.slice is not a function
course: The Complete 2024 Web Development Bootcamp

### ✔️ Expected Behavior

I expected the download to work.

### 🔍 Additional context

Win11

**Comment by heliomarpm** [comment]
More information, please

**Comment by geobruce** [comment]
![image](https://github.com/user-attachments/assets/995d11cd-cedb-4624-aedd-44e77dd5ffed)
When I click the downoad button.

[udeler_logger.txt](https://github.com/user-attachments/files/18053975/udeler_logger.txt)

I get the following, what other info can I provide to help you?

![image](https://github.com/user-attachments/assets/5b18a3ba-937c-4974-a568-6310658ec101)

**Comment by Beaniiman** [comment]
I have the same issue, first time trying the app but it fails with the same error.

**Comment by Maachaotmane** [comment]
The issue has been resolved in this PR. Awaiting approval.
https://github.com/heliomarpm/udemy-downloader-gui/pull/228

**Comment by heliomarpm** [comment]
See the new version 1.14
