### ISSUE TITLE
DRM PROTECTION

### ISSUE THREAD

**Issue by hassankhan2608** [heliomarpm/udemy-downloader-gui#227]
### Udeler | Udemy Course Downloader

1.13.4

### Account Type?

Personal

### Steps to reproduce

login and download the course 

it loads and then it says  CONTAIN DRM PROTECTION and cannot be downloaded

![image](https://github.com/user-attachments/assets/4757f817-959d-4e09-bf42-440602817dea)

no logs nothing

### ✔️ Expected Behavior

download course

**Comment by zakimimit** [comment]
the same problem

**Comment by heliomarpm** [comment]
#151
