### ISSUE TITLE
Login issue 

### ISSUE THREAD

**Issue by Chetia1991** [heliomarpm/udemy-downloader-gui#23]
When I put my udemy account details into udeler it login into a new window didn't come back to the udeler interface. Can you please help me with it?
![Udeler](https://user-images.githubusercontent.com/23296230/154539102-3b536cf2-6564-4393-9eba-39fc2f91b355.jpg)

**Comment by heliomarpm** [comment]
enter the configuration session and update

**Comment by Chetia1991** [comment]
Chrome didn't allow me to add your extension now what to do sir? The same login issue is coming sir.
![Udeler A E](https://user-images.githubusercontent.com/23296230/155272778-97eb4dcb-3546-4cb7-aebf-e4b6fc6a2442.jpg)

**Comment by heliomarpm** [comment]
> Chrome didn't allow me to add your extension now what to do sir? The same login issue is coming sir.
> ![Udeler A E](https://user-images.githubusercontent.com/23296230/155272778-97eb4dcb-3546-4cb7-aebf-e4b6fc6a2442.jpg)
> 

this extension has been deprecated.  Which version are you using?

**Comment by Chetia1991** [comment]
This version sir.

**Comment by elfumondice** [comment]
I'm also having login issues but with udemy business, it opens the page easily but after put my login and password it stays blank

**Comment by heliomarpm** [comment]
Gentlemen, Udemy recently made changes to the login, but the fixes were already implemented a few versions ago.
Please keep the updated version which should resolve the issue.
(https://github.com/heliomarpm/udemy-downloader-gui/releases)

**Comment by fi5ly** [comment]
Some login issue here, I'm using Windows 11 64

**Comment by Chetia1991** [comment]
Thank you so much for your response and support.
