### ISSUE TITLE
problems downloading

### ISSUE THREAD

**Issue by johnandrade18** [heliomarpm/udemy-downloader-gui#24]
I have a little concern in the short or free courses to download normal but when they are paid or many videos this error appears

![2022-02-21 08_46_17-](https://user-images.githubusercontent.com/10930368/154967696-91dc261c-7a7d-40dc-8321-d2fa07b16f3c.png)

**Comment by heliomarpm** [comment]
These courses are DRM protected, cannot be downloaded!
