### ISSUE TITLE
Get an error after logged in >>> Forbidden 

### ISSUE THREAD

**Issue by MGadAllah** [heliomarpm/udemy-downloader-gui#26]
After login, I get an error when loading courses.
Forbidden screen.
https://i.imgur.com/yDvVXt7.png

**Comment by heliomarpm** [comment]
Hi, could you try again. I tested it on several PCs with no problem, it may have been something momentary

**Comment by MGadAllah** [comment]
>  it may have been something momentary
Yes you are right, it is working now.
