### ISSUE TITLE
Building Course Data Again

### ISSUE THREAD

**Issue by pilot513** [heliomarpm/udemy-downloader-gui#27]
I used version 1.11.0 and have some problem. When I try download, I see "Building course Data". Opposite all browsers (Opera, Vivaldi, Firefox) show me movies correctly.

**Comment by heliomarpm** [comment]
this is a timeout problem, server returns gateway timeout and freezes the card.
I'm sending an update to handle the freeze

**Comment by pilot513** [comment]
It's very useful from your side. When patch will be ready, I check it.
Thank you for help!

**Comment by pilot513** [comment]
I install 1.11.1    Problem repeats. The download process waiting "Building Course Data"

**Comment by heliomarpm** [comment]
What course?

**Comment by pilot513** [comment]
I didn't quite understand. I just installed the updated version, hoping that the error will disappear. But the download does not happen, unfortunately.

**Comment by heliomarpm** [comment]
OK.  I will buy this course tomorrow and do some tests

**Comment by pilot513** [comment]
Thank you very much, you are so kind. I think you will eventually figure out what the problem is. Problems are not only with this course. I don't know why, but I suspect that Udemy has switched to streaming. So, Video DownloadHelper also does not see the presence of videos in such courses.

**Comment by heliomarpm** [comment]
> Thank you very much, you are so kind. I think you will eventually figure out what the problem is. Problems are not only with this course. I don't know why, but I suspect that Udemy has switched to streaming. So, Video DownloadHelper also does not see the presence of videos in such courses.

Sorry @pilot513 , i still cannot reproduce the problem.
About what you said earlier, I believe you are talking about the DRM protection applied by Udemy, in the Udeler options you can bypass encryption to continue the download, but this only serves to continue downloading attachments and any videos without encryption, sorry if it doesn't leave that's clear.

![Captura de tela 2022-03-13 190745](https://user-images.githubusercontent.com/13087389/158081480-49a6fff4-2f54-42bd-8cc1-05e65471692f.png)

**Comment by heliomarpm** [comment]
I'm still looking for an improvement on these downloads. But the more time passes, the more I believe I will have to rewrite Udeler entirely

**Comment by pilot513** [comment]
![изображение](https://user-images.githubusercontent.com/28645933/158109366-3889fe78-7005-466f-bf90-9b29a22c0597.png)

**Comment by fi5ly** [comment]
Same issue here, stuck on `Building course data `

![image](https://user-images.githubusercontent.com/1034658/158298227-9dc97c5e-7137-45e9-a993-21384e0b2a5d.png)

**Comment by fi5ly** [comment]
Hi, I successfully download the video, just roll back to version 1.6.2 

First step I install using version 1.11.1 then install to version 1.6.2

![image](https://user-images.githubusercontent.com/1034658/158303434-6ac3fbd2-55b8-4e43-aed7-0d574fa475d9.png)

**Comment by MEDO3ABED** [comment]
Same issue here in last update v1.11.1 , stuck on Building course data on Windows 10 64
