### ISSUE TITLE
Error Logging In 

### ISSUE THREAD

**Issue by saifkaral** [heliomarpm/udemy-downloader-gui#29]
idk why but every time I log in with google the screen just refreshes and nothing happens

**Comment by efdalsahin** [comment]
I have the same issue. Just about 5 minutes ago ı downloaded a course. And accidently log out. Now ı cant log in.

**Comment by heliomarpm** [comment]
Check new version
https://github.com/heliomarpm/udemy-downloader-gui/releases/latest.
