### ISSUE TITLE
Wrong LINK to download program!!!

### ISSUE THREAD

**Issue by michaelmiscanuk** [heliomarpm/udemy-downloader-gui#3]
Hi, I was having a problem to download program - release 1.9.1 for windows, and found that you have wrong link there.

It should be with underscores, but you have with hyphens:
```
https://github.com/heliomarpm/udemy-downloader-gui/releases/download/v1.9.1/udeler.Setup.1.9.1.Win-x64.exe
```
should be:
```
https://github.com/heliomarpm/udemy_downloader_gui/releases/download/v1.9.1/udeler.Setup.1.9.1.Win-x64.exe
```
You might want to correct it.

**Comment by heliomarpm** [comment]
Thanks @michaelmiscanuk ;
