### ISSUE TITLE
Downloading with a personnel subscription

### ISSUE THREAD

**Issue by cantercrow** [heliomarpm/udemy-downloader-gui#34]
I can't download videos as I have a personnel subscription and the videos I am watching don't show up.

**Comment by heliomarpm** [comment]
Which version are you using?
Is the logged in user enrolled in a course on Udemy?
Are you connecting with google or username and password? Is it a business account?
If possible send a screenshot

**Comment by camille-bigot** [comment]
i am also facing this issue. I have a personal plan account and when i login into Udeler, it says "No Courses Found". While i am watching few courses on web/app. @heliomarpm if you need an testing account to reproduce this issue( Testing account cause it doesn't work only with personal plan accounts) lemme know i will provide.
Thanks

**Comment by camille-bigot** [comment]
@heliomarpm Hey! Sorry for delayed response. Umm, i still can't see any course when i login(personal plan) although normal account works fine. 
For the personal plan account i tried login via email/password and cookies and still have no success.

What have i tried?
Start watching an course 
Add it to watchlater

Than trying to login via email/password
Than try to login via access token 
Nothing else

I can either post the access token here or mail you( as you say).
![image](https://user-images.githubusercontent.com/98650182/180411756-8fd8f079-e8b5-490e-a7b6-733625f23973.png)

**Comment by heliomarpm** [comment]
Hi Camile, sorry for the delay, if you're still having problems I'll be happy to help.

If you don't mind sending me your username and password, I just ask you to change the password as soon as you finish testing, I'll be more relaxed with that 😊
You can send it to heliomarpm@gmail.com
