### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by tonyroo** [heliomarpm/udemy-downloader-gui#36]
can't login please help. after add email and password app restart

**Comment by heliomarpm** [comment]
Which version are you using?
Are you connecting with google or username and password? Is it a business account?
If possible send a screenshot

**Comment by techfordummiesmm** [comment]
![image](https://user-images.githubusercontent.com/50479345/161458534-af46da1f-aa40-4f82-8b9d-0d77fe05e792.png)

I can't download, when I am login

**Comment by heliomarpm** [comment]
Update
https://github.com/heliomarpm/udemy-downloader-gui/releases
