### ISSUE TITLE
Error in 75% part

### ISSUE THREAD

**Issue by ynsygt271** [heliomarpm/udemy-downloader-gui#38]
It gives an error after downloading the videos by 75%! I get a "click to download again" warning.  I've included a picture below showing the before and after situations.
![Ekran Alıntısı1](https://user-images.githubusercontent.com/103308554/162563735-39a971de-8d8c-47a8-9000-930827ba167c.JPG)
![Ekran Alıntısı2](https://user-images.githubusercontent.com/103308554/162563737-2785222a-5d16-49cf-9886-479ef88d46eb.JPG)

**Comment by heliomarpm** [comment]
I will be making available a new version that should be able to present the error, so you can send me the error for evaluation ok

**Comment by heliomarpm** [comment]
Check the new version
https://github.com/heliomarpm/udemy-downloader-gui/releases/latest.
