### ISSUE TITLE
Infinityp

### ISSUE THREAD

**Issue by arjanv** [heliomarpm/udemy-downloader-gui#4]
what does the "error" Infinityp mean?

**Comment by darthobiguan** [comment]
I have a couple of courses with -infinityp also. Here is the screenshot of it. I tried disabling subtitle and other options, no luck.

![image](https://user-images.githubusercontent.com/95434091/144462835-7724110c-b574-48fe-993e-cebeac26d607.png)

**Comment by edy-dev** [comment]
Infinite loop or something like that. Simply this course does not download, others yes without problems.
Print Error
https://i.imgur.com/d8zWmKs.png

Note to developers: Thank you for sustaining this project, this project is helping a lot of people.

**Comment by heliomarpm** [comment]
These videos are encrypted with DRM, Udeler is not able to break encryption. 
In some cases the download gets stuck, unfortunately

**Comment by heliomarpm** [comment]
> what does the "error" Infinityp mean?

It is usually associated with encrypted videos, no practical solution for this

**Comment by darthobiguan** [comment]
Hi Heliorpm,

Thanks for updating and keeping this project alive. This program has help me tremendously. I was googling on the encrypted video in udemy and found this. Maybe this helps in decrypting the video. I haven't try this myself yet. 

https://pythonrepo.com/repo/Puyodead1-udemy-downloader-python-downloader

**Comment by heliomarpm** [comment]
> Hi Heliorpm,
> 
> Thanks for updating and keeping this project alive. This program has help me tremendously. I was googling on the encrypted video in udemy and found this. Maybe this helps in decrypting the video. I haven't try this myself yet. 
> 
> https://pythonrepo.com/repo/Puyodead1-udemy-downloader-python-downloader
> 
> 

Thanks, i'll take a look and come back if i have any news

**Comment by edy-dev** [comment]
> Hi Heliorpm,
> 
> Thanks for updating and keeping this project alive. This program has help me tremendously. I was googling on the encrypted video in udemy and found this. Maybe this helps in decrypting the video. I haven't try this myself yet.
> 
> https://pythonrepo.com/repo/Puyodead1-udemy-downloader-python-downloader

I still can't download it. I can't find the Key

**Comment by heliomarpm** [comment]
Check the last version, please

**Comment by heliomarpm** [comment]
Resolved crash
