### ISSUE TITLE
No Courses Found

### ISSUE THREAD

**Issue by KafiebRo** [heliomarpm/udemy-downloader-gui#47]
whenever i search for any course, it shows no courses found. Help needed!
![Screenshot 2022-04-28 174914](https://user-images.githubusercontent.com/104568502/165745711-807a83b3-a5e5-461a-83b4-586f3e255d90.png)

**Comment by heliomarpm** [comment]
Are you enrolled in any courses? 
The logged in user must be enrolled in a Udemy course!

**Comment by KafiebRo** [comment]
> Are you enrolled in any courses? 
> The logged in user must be enrolled in a Udemy course!

Yes i did. Still not working at All.
![Screenshot_2022-04-29-12-45-35-457_com.udemy.android.jpg](https://user-images.githubusercontent.com/104568502/165896570-5c7873f9-0b7d-407a-ae35-8c022e4aa8c6.jpg)

**Comment by heliomarpm** [comment]
You searched for python, the title of this course does not contain that word
