### ISSUE TITLE
Login Issue - No Redirect

### ISSUE THREAD

**Issue by Cm13my** [heliomarpm/udemy-downloader-gui#5]
Can't Login.
After logging in the credentials, The app just redirects to Udemy Website
it does not shows Udeler UI Anymore ( No Courses)
Only showing Udemy Webpage in App itself

Please check

![image](https://user-images.githubusercontent.com/96164151/146130105-9308de60-cf05-474c-85f0-319c7c6d5b4c.png)

**Comment by iamsaba** [comment]
I am getting the same issue as well. Please HELP!!!

**Comment by MEDO3ABED** [comment]
I am getting the same issue as well. Please HELP!!!

**Comment by abbeynet77** [comment]
I have the same issue here as well. Please help out.

**Comment by atayserdar** [comment]
I have the same issue

**Comment by heliomarpm** [comment]
The problem is already being verified, for now it is possible to connect only with access_token

**Comment by heliomarpm** [comment]
https://github.com/heliomarpm/udemy-downloader-gui/issues/5
