### ISSUE TITLE
Left panel (controls) is missing

### ISSUE THREAD

**Issue by NyanCod3r** [heliomarpm/udemy-downloader-gui#50]
### Udeler | Udemy Course Downloader

1.8.2

### Running as Business Account

- [ ] Yes

### Steps to reproduce

After login with Udemy credentials the left panel to control downloads and courses is missing. It never worked for me. 

### ✔️ Expected Behavior

I'm expecting to see the control panel to download the courses.

### ❌ Actual Behavior

I can only access Udemy page. No issues there.
![Capture](https://user-images.githubusercontent.com/60844713/167653858-df3510d4-08a8-46e9-93cd-d4ebf90b1ddb.PNG)

**Comment by heliomarpm** [comment]
Please,  install the latest version.
Note that login with Google is having problems

**Comment by NyanCod3r** [comment]
Indeed, version upgrade did the trick
