### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by PhamXuanThe** [heliomarpm/udemy-downloader-gui#53]
### Udeler | Udemy Course Downloader

1.11.2

### Running as Business Account

- [ ] Yes

### Steps to reproduce

![Screenshot 2022-05-29 075459](https://user-images.githubusercontent.com/105701889/170847551-9eaf9207-cca1-404c-9e7a-2daea0acbf82.jpg)

Hi.
I'm having a problem logging in.
I'm using 1.11.2 when the tool logout and can't login back. You can see the attached image.
However, sometimes I can login again and it exits on its own.
I don't understand what the problem.
Can you help?

### ✔️ Expected Behavior

Click to login button (Credentials and token)

### ❌ Actual Behavior

![Screenshot 2022-05-29 074722](https://user-images.githubusercontent.com/105701889/170847543-56ae5b33-80ba-48ed-942b-a8dfbb3867b7.jpg)

**Comment by efdalsahin** [comment]
I have the same issue. Just about 5 minutes ago ı downloaded a course. And accidently log out. Now ı cant log in.

**Comment by heliomarpm** [comment]
resolved
