### ISSUE TITLE
not download

### ISSUE THREAD

**Issue by leandrodopl** [heliomarpm/udemy-downloader-gui#54]
### Udeler | Udemy Course Downloader

1.11.2

### Running as Business Account

- [ ] Yes

### Steps to reproduce

![image](https://user-images.githubusercontent.com/106984626/172190709-5ceb7ba3-5db2-42fd-83dd-589ae113b370.png)

![image](https://user-images.githubusercontent.com/106984626/172190818-b75fec7b-fb99-428d-9420-80fec44a6d7b.png)

**Comment by heliomarpm** [comment]
Please, delete all .MTD files, and try again

**Comment by heliomarpm** [comment]
Esse curso Engenharia Reversa, chegou a iniciar o download?

**Comment by elomoery** [comment]
today no more setup
please  need  update

**Comment by burnham** [comment]
Hi, I can not download because of the DRM protection...
 
![image](https://user-images.githubusercontent.com/249632/173909396-e2d5147e-189e-4287-bf18-b7fb4cabef01.png)


Tnks in advance.

**Comment by heliomarpm** [comment]
> today no more setup
> please  need  update

I don't understand, what's missing?

**Comment by heliomarpm** [comment]
> Hi, I can not download because of the DRM protection...
>  
> ![image](https://user-images.githubusercontent.com/249632/173909396-e2d5147e-189e-4287-bf18-b7fb4cabef01.png)
> 
> 
> Tnks in advance.

Hi, DRM protection requires a second key to decrypt, which we don't have possession of, unfortunately we can't download videos without it.

**Comment by totti240282** [comment]
errorDownload
Invalid file path: T:\xx\Udemy/xxxxx.mp4.mtd
