### ISSUE TITLE
Unable to login - getting redirected past main menu

### ISSUE THREAD

**Issue by leonsp95** [heliomarpm/udemy-downloader-gui#57]
### Udeler | Udemy Course Downloader

1.11.2

### Running as Business Account

- [ ] Yes

### Steps to reproduce

I'm experiencing a strange problem: I can't login at all. No messages, no warns, no error msgs. As soon as I click the login button, I get redirected to the main page again. I was able to login and download things normally around one week ago.

![image](https://user-images.githubusercontent.com/46500277/175925172-5e03b110-0eeb-4fe0-84ae-47d3d8e77a69.png)
![image](https://user-images.githubusercontent.com/46500277/175924392-f47b6b89-66e6-4a9a-b36c-54f7caed7419.png)
![image](https://user-images.githubusercontent.com/46500277/175924409-5ba281d6-db32-4aea-beaf-b6df20abcfa2.png)

### ✔️ Expected Behavior

Succesful login after clicking the button.

### ❌ Actual Behavior

Redirected to the main menu.

**Comment by heliomarpm** [comment]
Leo blz?
Logo depois de tentar o login, clique no  botão do menu lateral que fica logo abaixo do botão Sobre e veja se tem alguma mensagem, por favor.

**Comment by heliomarpm** [comment]
Unidentified issue in version 1.11.3
