### ISSUE TITLE
courses video error

### ISSUE THREAD

**Issue by mashroom-lab** [heliomarpm/udemy-downloader-gui#59]
hello sir latest app/software downloading courses very well but when I play the course's videos it's not completed some video parts are half video timer shows that the video is playing but the voice and picture are not shown and I am redownloading that particular video again by IDM downloader please solve this issue thanks

**Comment by heliomarpm** [comment]
Hello, please reopen this problem using the template, if possible include screenshots and inform the course and which lecture is having a problem. This information is important for reproducing the issue.
