### ISSUE TITLE
with zero to the left activated, if it is already downloaded without zero, it does not rename the .srt file with zero to the left

### ISSUE THREAD

**Issue by streikpc** [heliomarpm/udemy-downloader-gui#60]
### Udeler | Udemy Course Downloader

1.11.3

### Running as Business Account

- [ ] Yes

### Steps to reproduce

if you download a course with leading zero enabled,
that had already been downloaded before, without zero to the left.

The .mp4 file does put a zero on the left.
But the .SRT file of subtitles (which was previously downloaded) DOES NOT PUT THE ZERO TO THE LEFT.
-------
with zero to the left activated, if it is already downloaded without zero, it does not rename the .srt file with zero to the left

### ✔️ Expected Behavior

I expected it to put leading zero in downloaded sion .srt files, to put leading zero in subtitle .srt files.
I should have put in the file .SRT:   "01. Lesson of course of for example one thing.srt"

Because there are more than 9 lessons in the same section.

### ❌ Actual Behavior

the .srt file stays with:  "1.- Lesson of course of for example one thing.srt"

Because there are more than 9 lessons in the same section.

**Comment by heliomarpm** [comment]
> and randomly, some .mp4 files are also not renamed with leading zero.

Important to note that zero will be included only if the chapter contains 10 or more lessons

**Comment by heliomarpm** [comment]
Sorry, I thought this problem was already fixed. I will investigate. Thanks for reporting.

**Comment by heliomarpm** [comment]
Unidentified issue in version 1.11.3
