### ISSUE TITLE
there may be some new protection system d** for some videos.

### ISSUE THREAD

**Issue by streikpc** [heliomarpm/udemy-downloader-gui#61]
### Udeler | Udemy Course Downloader

1.11.3

### Running as Business Account

- [ ] Yes

### Steps to reproduce

there may be some new protection system d** for some videos.

should download the videos, (starts to happen with some courses). But it doesn't download them.
Only videos that are not protected are downloaded.

If it downloads all the .srt subtitle files, that's fine.
But the videos are not downloaded. It skips them, directly.

And it skips all but 2, which are the ones that are not protected.
 The protected ones are not downloaded.

I think it's that.

**Comment by heliomarpm** [comment]
This is normal behavior, Udeler will not download protected videos.
Optionally, you can configure to stop the download if any protected video is found.
Continuing the download can be interesting if you want to download the extra files added occasionally in classes
