### ISSUE TITLE
stands in an election even OPEN TO THE PUBLIC. And it just stands there, and it doesn't download, neither this reading, nor any of the following readings.

### ISSUE THREAD

**Issue by streikpc** [heliomarpm/udemy-downloader-gui#62]
### Udeler | Udemy Course Downloader

1.11.3

### Running as Business Account

- [ ] Yes

### Steps to reproduce

stands in an election even OPEN TO THE PUBLIC. And it just stands there, and it doesn't download, neither this reading, nor any of the following readings.

Clues to guess or know what happens:
* The lesson is called:
2. Who is your instructor?

But the file it tries to create is named without the final question mark:
2. Who is your instructor.mp4

I say this, for what it's worth.

And above the photograph, to the left, put: autop

**Comment by heliomarpm** [comment]
Hello, this is normal behavior, files are created without the special characters not supported by Windows.

The AUTOP information may be an indication that this lesson may be protected, if this is the case it will not be possible to download it.

Could you please tell me the name of the course?
