### ISSUE TITLE
quality 1080

### ISSUE THREAD

**Issue by suleimanovs** [heliomarpm/udemy-downloader-gui#63]
### Description of the new feature / enhancement

I can’t download in 1080 quality. It was the same in previous versions, even Udeler had this

### Scenario when this would be used?

I can’t download in 1080 quality. It was the same in previous versions, even Udeler had this

**Comment by heliomarpm** [comment]
Hi, Udeler doesn't convert the video quality, it just downloads the qualities provided by the Udemy API.

When the option is not found, the download will be done in the highest quality available.
Doing an automatic conversion can make Udeler very slow.

Sorry, I hope to keep getting new orders

**Comment by heliomarpm** [comment]
Available in version 1.11.5.
https://github.com/heliomarpm/udemy-downloader-gui/releases/latest

**Comment by suleimanovs** [comment]
Sorry, but the maximum quality is 720
![image](https://user-images.githubusercontent.com/77715479/215287170-d9b1b2fd-d9fe-41c8-b2f4-9f1cd67ecc44.png)

**Comment by heliomarpm** [comment]
Select the Highest option.
The maximum quality available on Udemy is 1080p, if you choose the highest it will download.
Please note that this resolution will only download if available on Udemy

**Comment by heliomarpm** [comment]
> Hi,
> 
> I downloaded 1080p but some video is not downloaded. some files its shown me MDT format and .SRT
Videos with DRM protection are not downloaded
