### ISSUE TITLE
Stuck on Building Course Data

### ISSUE THREAD

**Issue by hassanayoub1985** [heliomarpm/udemy-downloader-gui#67]
1.11.3 on win11 stuck on "Building Course Data" and don't save changed settings

**Comment by heliomarpm** [comment]
Please, what is the name of the course?

**Comment by hassanayoub1985** [comment]
https://www.udemy.com/course/hls-combinational-circuits
https://www.udemy.com/course/hands-on-zynq-mastering-axi4-bus-protocol

**Comment by venky9885** [comment]
Same issue facing

**Comment by venky9885** [comment]
I have set Video Quality to 720 and Set Tick in video protected DRM in settings Then Everything has downloaded
But the most of videos have not downloaded Instead .srt Extension Files are downloaded
Please Rectify Issue

My course:
https://www.udemy.com/course/algorithmic-problems-in-python/

**Comment by atuxnull** [comment]
i face the issue no matter which course i choose from Udemy.

**Comment by heliomarpm** [comment]
Option to bypass DRM protection, it only serves to continue downloading attachments and available videos.

**Comment by safakyavsan** [comment]
I have same issue for all courses I have

**Comment by heliomarpm** [comment]
> I have same issue for all courses I have click the skip atttachments option in the settings solve that

Please note that this option is only for downloading attachments and other unlocked classes ok. Will not download encrypted lessons

**Comment by vladlearns** [comment]
Make sure you change the folder in setting and save the changes. Since the save button is hidden in the bottom of the screen, I had to guess that I need to click it.

**Comment by heliomarpm** [comment]
> Make sure you change the folder in setting and save the changes. Since the save button is hidden in the bottom of the screen, I had to guess that I need to click it.

this has been modified in the latest versions, the save button is now always visible

**Comment by vladlearns** [comment]
@heliomarpm Yeap, now it is fixed. So, maybe we can close this one as outdated?
