### ISSUE TITLE
I think there's a bug that doesn't download to 1080p

### ISSUE THREAD

**Issue by radic2682** [heliomarpm/udemy-downloader-gui#68]
### Udeler | Udemy Course Downloader

1.11.3

### Running as Business Account

- [ ] Yes

### Steps to reproduce

on win11
I was going to download it to 1080p, but I cant.
I definitely set it up and saved it. but it still download 720p.

Thank you for your hard work.
Please fix it.

### ✔️ Expected Behavior

can downlaod to 1080p

### ❌ Actual Behavior

it still download 720p.

**Comment by heliomarpm** [comment]
## Available in version 1.11.5
- Download video streams (M3U8) - Contributed by @CetinOzdil  #87
