### ISSUE TITLE
No Courses Found

### ISSUE THREAD

**Issue by vedantsingh650** [heliomarpm/udemy-downloader-gui#7]
After the fix of commit id de037d0ea2af55f59b5c5f040f019fe860b97201 "hotfix login with token" .
I download the software and Login with the Access Token .
Getting response "No courses Found" .

![Screenshot (123)](https://user-images.githubusercontent.com/26855621/146647732-6086817d-ca1a-4a31-971a-3f72d11e5bf4.png)

**Comment by heliomarpm** [comment]
Get the latest version
https://github.com/heliomarpm/udemy-downloader-gui/releases/tag/v1.10.2

**Comment by vedantsingh650** [comment]
Still I am facing same issue . No Courses Found
