### ISSUE TITLE
Download stops

### ISSUE THREAD

**Issue by mezarlikbekcisi** [heliomarpm/udemy-downloader-gui#70]
### Udeler | Udemy Course Downloader

1.11.04

### Running as Business Account

- [ ] Yes

### Steps to reproduce

My download with Udeler stops after a while even though the course is not completed and it shows the download speed as 0.00 KB. When I close and open the program, 1 video downloads again and the download stops again. There is no continuity.

**Comment by heliomarpm** [comment]
Can you tell me which course?
