### ISSUE TITLE
Can't login Udemy Business account!

### ISSUE THREAD

**Issue by coderminhaj** [heliomarpm/udemy-downloader-gui#71]
### Udeler | Udemy Course Downloader

1.11.4

### Running as Business Account

- [ ] Yes

### Steps to reproduce

<img src="https://images2.imgbox.com/e7/6b/1Bqz2RrM_o.png" alt="image host"/>

### ✔️ Expected Behavior

It should log in like it was logged in before

### ❌ Actual Behavior

the the login window hanged up

**Comment by dbranco** [comment]
Remove the www and place your business name

**Comment by heliomarpm** [comment]
for business url remove www
