### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by selenofobico** [heliomarpm/udemy-downloader-gui#72]
### Provide a description of requested docs changes

**# _It has a solution?_**

![Captura de pantalla (15)](https://user-images.githubusercontent.com/5233084/187045447-e2cef1dc-d021-4427-8792-a05fa0f5d2e0.png)

**Comment by rickeymandraque** [comment]
Hello,
https://github.com/heliomarpm/udemy-downloader-gui#warning
unless you have the encryption keys to use with udemy-downloader, there are no solutions.

**Comment by heliomarpm** [comment]
Thanks @rickeymandraque

**Comment by heliomarpm** [comment]
The Skip option is just to continue downloading the available files and videos.
