### ISSUE TITLE
sort list courses

### ISSUE THREAD

**Issue by cemkara67** [heliomarpm/udemy-downloader-gui#74]
### Description of the new feature / enhancement

In the new version, the course list is mixed.
In older versions, the last lesson learned was at the top.
Please solve this problem

### Scenario when this would be used?

In the new version, the course list is mixed.
In older versions, the last lesson learned was at the top.
Please solve this problem

**Comment by heliomarpm** [comment]
the list has always been in order of subscription, I will mark your question as a new feature

**Comment by cemkara67** [comment]
Please put the most recently recorded courses at the top.

**Comment by heliomarpm** [comment]
version 1.12.7
