### ISSUE TITLE
courses cannot download

### ISSUE THREAD

**Issue by apriladwork** [heliomarpm/udemy-downloader-gui#77]
### Udeler | Udemy Course Downloader

1.11.4

### Running as Business Account

- [ ] Yes

### Steps to reproduce

it stucking at "building course data".
![Screenshot_1](https://user-images.githubusercontent.com/117488840/200085494-4e8bc97a-d8b5-4f7a-951c-f6790072d09b.png)

**Comment by apriladwork** [comment]
any help? :'(

**Comment by droblesauter** [comment]
Same issue here

**Comment by heliomarpm** [comment]
I will continue to look for a solution to this problem, gentlemen.

**Comment by apriladwork** [comment]
thanks @heliomarpm.
do you have any update?

**Comment by heliomarpm** [comment]
Hi, send a screenshot the menu Logger, please.

**Comment by heliomarpm** [comment]
> thanks @heliomarpm.
> do you have any update?

Hi, send a screenshot the menu Logger, please.

**Comment by yooo1999** [comment]
Same issue here

**Comment by Mawley779** [comment]
![01](https://user-images.githubusercontent.com/124076865/215830717-eceebd90-8b66-42c0-ba23-8a091d38b1a5.PNG)


I am having a similar issue. On this 9th video it gets to the end of the download and just freezes like this. I have tried several times with the same thing happening every time.

**Comment by deivsonbf** [comment]
![image](https://user-images.githubusercontent.com/25336725/217270614-f3606bf9-43a2-466a-984c-2d857d4bb2aa.png)

**Comment by heliomarpm** [comment]
> ![01](https://user-images.githubusercontent.com/124076865/215830717-eceebd90-8b66-42c0-ba23-8a091d38b1a5.PNG)
> 
> 
> I am having a similar issue. On this 9th video it gets to the end of the download and just freezes like this. I have tried several times with the same thing happening every time.

Please, send me Logger message.

**Comment by Agonymous** [comment]
How do you even managed to download in 1080p? I can download the exact same course but only in 720p. It stops sometimes but I use the restart download option.

**Comment by heliomarpm** [comment]
> How do you even managed to download in 1080p? I can download the exact same course but only in 720p. It stops sometimes but I use the restart download option.

by your print you are already downloading the highest resolution, this course probably doesn't have videos in 1080p.  I'm going to try to buy this course, so I'll be sure if it offers this resolution or not

**Comment by Agonymous** [comment]
> > How do you even managed to download in 1080p? I can download the exact same course but only in 720p. It stops sometimes but I use the restart download option.
> 
> by your print you are already downloading the highest resolution, this course probably doesn't have videos in 1080p. I'm going to try to buy this course, so I'll be sure if it offers this resolution or not

Mawly779 shows that he can download in 1080p, I also downloaded one video over jdownloader via the vlc extension in firefox in 1080p.

**Comment by heliomarpm** [comment]
> I now managed to download it on 1080p but have the same problem as Mawley779. It stops after video 8. I saw that the title of the video has a / (slash) in it's name. Maybe that causes the problem? Because you can't use / in file names.

yes, that can be a problem.  Thanks for reporting, I'll check

**Comment by heliomarpm** [comment]
Added a bug tracking library, hope to find the root of the problem soon

**Comment by rahujm** [comment]
Cant able to download DRM protected videos

**Comment by heliomarpm** [comment]
> Cant able to download DRM protected videos
> ![image](https://user-images.githubusercontent.com/127341559/223805749-aff60885-3219-461d-b0b3-12c1cd07d738.png)
> 

This tool does not download protected videos, is't an issue.
