### ISSUE TITLE
[BUG] Controls are going disappear after first video downloaded

### ISSUE THREAD

**Issue by mrsksir** [heliomarpm/udemy-downloader-gui#8]
### No controls are showing after first video downloaded.

> Note: Wait at least 5 video are downloaded to see error because it's depends on PC

Udeler Version: 1.10.2 (Latest)

**Steps to reproduce bug:**
1. Login with udemy credential 
2. Enable following Settings
_[You must have to enabled first to reproduce issue on your machine]_**

     ![image](https://user-images.githubusercontent.com/32188436/146661205-0c70db8d-8ef9-4891-a864-3c0d8f4533e5.png)

2. Select course to download 
3. Click on download button
4. Wait until first video downloaded 
5. After that you can see all controls are going disappear like below screenshots

**Screenshots**
![image](https://user-images.githubusercontent.com/32188436/146660966-1637ffc5-33df-4167-b87b-6202b7f1b17a.png)

**Comment by heliomarpm** [comment]
Sorry, Udemy's api is changing frequently.
Check the last vesion

**Comment by mrsksir** [comment]
Ok 
Let me try.

**Comment by heliomarpm** [comment]
Resolved in version 1.10.3
