### ISSUE TITLE
can't install Udeler Authenticator

### ISSUE THREAD

**Issue by islamEL-Menshawy** [heliomarpm/udemy-downloader-gui#80]
### Udeler | Udemy Course Downloader

1.11.2

### Running as Business Account

- [ ] Yes

### Steps to reproduce

after download extention and enable devoloper mode and drage file in extensions page that apper massage This extension is not listed in the Chrome Web Store and may have been added without your knowledge.

**Comment by jawad-r3** [comment]
Just un pack the extension using WinRAR or 7zip. Enable Developer mode in chrome extensions and load unpacked extension.

**Comment by heliomarpm** [comment]
Sorry I didn't create this extension and I don't have the source code.
It was developed in the old versions.

Can you tell me what it's for?
