### ISSUE TITLE
LOG files

### ISSUE THREAD

**Issue by mickybusy** [heliomarpm/udemy-downloader-gui#85]
### Description of the new feature / enhancement

I use Udeler on Windows and I would like to have a file that contains a copy of the Logger information, so that I don't have to do a copy paste manually. How can I achieve such a thing?

### Scenario when this would be used?

This allows for a reminder of any protected or problem parts of a downloaded

**Comment by heliomarpm** [comment]
@mickybusy 
Available in version 1.11.5.
https://github.com/heliomarpm/udemy-downloader-gui/releases/latest
