### ISSUE TITLE
The option only downloads attachments and subtitles

### ISSUE THREAD

**Issue by delcom-itdel** [heliomarpm/udemy-downloader-gui#86]
### Description of the new feature / enhancement

Is it possible to make the option to only download subtitles and attachments?

### Scenario when this would be used?

I just want to download the attachments and subtitles of the course I have.

**Comment by heliomarpm** [comment]
@delcom-itdel  
Available in version 1.11.5.
https://github.com/heliomarpm/udemy-downloader-gui/releases/latest
