### ISSUE TITLE
Not able to download the courses

### ISSUE THREAD

**Issue by iamsaba** [heliomarpm/udemy-downloader-gui#9]
Hi,

Thank you for sorting the redirect issue. I'm getting the following error now. Could this please be looked at?
`
`
![Udeler_Issue](https://user-images.githubusercontent.com/48571342/146769648-9bcefc3d-ec29-46e4-a744-d188d70b90c3.GIF)

**Comment by heliomarpm** [comment]
Sorry, videos blocked by encryption has no solution at the moment
