### ISSUE TITLE
Alguns vídeos não tem som, outros o vídeo pula pequenas partes

### ISSUE THREAD

**Issue by luizpatrocinio** [heliomarpm/udemy-downloader-gui#91]
### Udeler | Udemy Course Downloader

1.11.5

### Running as Business Account

- [ ] Yes

### Steps to reproduce

Após baixar todas a aulas algumas tem problemas como sem áudio e outras picotando o video (dando pequenos pulos)

### ✔️ Expected Behavior

Esperado como outros vídeos com som e sem problemas de pular pedaços. Todos so vídeos baixados pelo Udeler não apresentam problema assistindo no site da Udemy.

### ❌ Actual Behavior / Steps to Reproduce

1- Logar 
2 - Baixar
3 - Reproduzir
Configurações abaixo

![erroUdeler1-11-5](https://user-images.githubusercontent.com/16004201/212761326-c6b187b9-ad1a-4a81-a403-b871dbfdf513.jpg)

**Comment by heliomarpm** [comment]
Luiz me informe por favor qual o curso e qual resolução você baixou

**Comment by luizpatrocinio** [comment]
Escolhi a Resolução Máxima, tem de 720 e 1080.
o curso é esse: Curso de Django Web Framework e Django Rest Framework
os problemas começam tópicos 20 em diante toda com picote e falta de áudio.
Sem som: 18. Class Based Views com JsonResponse/2. Adicionando JSONResponse para a API que usa ListView
picotando: 22. Criando relações com o User Model do Django/4. Melhorando o desempenho das consultas com prefetch_related e select_related

Baixei duas vezes e cada vez veio com problemas em videos e audios diferentes

**Comment by luizpatrocinio** [comment]
Escolhi a Resolução Máxima, tem de 720 e 1080.
o curso é esse: Curso de Django Web Framework e Django Rest Framework
os problemas começam tópicos 20 em diante toda com picote e falta de áudio.
Sem som: 18. Class Based Views com JsonResponse/2. Adicionando JSONResponse para a API que usa ListView
picotando: 22. Criando relações com o User Model do Django/4. Melhorando o desempenho das consultas com prefetch_related e select_related

Baixei duas vezes e cada vez veio com problemas em videos e audios diferentes

**Comment by heliomarpm** [comment]
> Escolhi a Resolução Máxima, tem de 720 e 1080. o curso é esse: Curso de Django Web Framework e Django Rest Framework os problemas começam tópicos 20 em diante toda com picote e falta de áudio. Sem som: 18. Class Based Views com JsonResponse/2. Adicionando JSONResponse para a API que usa ListView picotando: 22. Criando relações com o User Model do Django/4. Melhorando o desempenho das consultas com prefetch_related e select_related
> 
> Baixei duas vezes e cada vez veio com problemas em videos e audios diferentes

Esse curso eu não tenho.
Os cursos que tenho não estão apresentando problema em nenhuma das resoluções, por favor me avise se tiver problemas em outro curso, vou continuar verificando

**Comment by luizpatrocinio** [comment]
Resolvido:

Alterei nas configurações:
Tentar reiniciar automaticamente em caso de erro (Experimental) DESABILITEI
Baixar apenas Aulas HABILITEI
Qualidade do vídeo: Auto

Agora todas as aulas estão ok.

Tks. Heliomar
