### ISSUE TITLE
Udemy course downloader 1.11.5 - DRM issue

### ISSUE THREAD

**Issue by mrkhanpathan** [heliomarpm/udemy-downloader-gui#93]
### Udeler | Udemy Course Downloader

1.11.5

### Running as Business Account

- [ ] Yes

### Steps to reproduce

not downloading DRM protected videos, its downloading only .srt files 

### ✔️ Expected Behavior

DRM protected videos need to be download 

### ❌ Actual Behavior / Steps to Reproduce

1.

**Comment by heliomarpm** [comment]
This software does not download copyrighted lessons
