### ISSUE TITLE
have an error with version 1.11.5

### ISSUE THREAD

**Issue by AmiraMostafa628** [heliomarpm/udemy-downloader-gui#95]
### Udeler | Udemy Course Downloader

1.11.5

### Running as Business Account

- [ ] Yes

### Steps to reproduce

![Screenshot 2023-02-20 163054](https://user-images.githubusercontent.com/103458291/220134821-7f9c07c6-78dd-4828-aa0f-23de07a8104b.jpg)

### ✔️ Expected Behavior

No response

### ❌ Actual Behavior / Steps to Reproduce

No response

**Comment by AmiraMostafa628** [comment]
![Screenshot 2023-02-20 163939](https://user-images.githubusercontent.com/103458291/220136158-e9f3b71b-252c-407a-8295-70d922788bfd.jpg)

**Comment by heliomarpm** [comment]
Hi.
This is a strange error because it is related to missing file.  Could you try again, if it happens again, tell me which class.

**Comment by xploz1on** [comment]
@AmiraMostafa628 Did you by any chance changed to download path name? Not in the app but in the system? This is an unusually error.

@heliomarpm Im on macOS Ventura 13.3 Beta (intel), built the app and it works PERFECT, no problem at all. Will try to update the packages and rebuild (Sorry didn’t t know where to post this).

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/13008386/220392077-2a8ff622-b144-4b93-903e-60be18581dae.png">

I don’t really work with NPM btw.

**Comment by heliomarpm** [comment]
> @AmiraMostafa628 Did you by any chance changed to download path name? Not in the app but in the system? This is an unusually error.
> 
> @heliomarpm Im on macOS Ventura 13.3 Beta (intel), built the app and it works PERFECT, no problem at all. Will try to update the packages and rebuild (Sorry didn’t t know where to post this).
> 
> <img width="1131" alt="image" src="https://user-images.githubusercontent.com/13008386/220392077-2a8ff622-b144-4b93-903e-60be18581dae.png">
> 
> I don’t really work with NPM btw. 

If you have made changes can you send a PR? 

Thanks for your help, I would really like to distribute to MacOs via GitHub Actions itself, but I don't have the necessary knowledge. 

 I've been trying to distribute for Linux as well but I'm still getting some errors.

**Comment by xploz1on** [comment]
I didnt make any changes at all. Cloning the repo and building macOS (intel) works without no problem. The package installs and runs perfect!

Now after updating the packages by npm the app doesn’t work anymore and even npm tells you the broken packages. I can share the dmg package for macOS.

I can help with github actions too! Just need to finish some IRL work!

**Comment by AmiraMostafa628** [comment]
> Hi. This is a strange error because it is related to missing file. Could you try again, if it happens again, tell me which class.

thanks, it works now

**Comment by heliomarpm** [comment]
> Eu não fiz nenhuma alteração. Clonar o repositório e criar o macOS (intel) funciona sem nenhum problema. O pacote é instalado e funciona perfeitamente!
> 
> Agora, depois de atualizar os pacotes por npm o aplicativo não funciona mais e até mesmo npm informa os pacotes quebrados. Eu posso compartilhar o pacote dmg para macOS.
> 
> Eu também posso ajudar com as ações do github! Só precisa terminar algum trabalho IRL!

Thank you for your help

**Comment by heliomarpm** [comment]
Added a bug tracking library, hope to find the root of the problem soon

**Comment by heliomarpm** [comment]
> Eu não fiz nenhuma alteração. Clonar o repositório e criar o macOS (intel) funciona sem nenhum problema. O pacote é instalado e funciona perfeitamente!
> 
> Agora, depois de atualizar os pacotes por npm o aplicativo não funciona mais e até mesmo npm informa os pacotes quebrados. Eu posso compartilhar o pacote dmg para macOS.
> 
> Eu também posso ajudar com as ações do github! Só precisa terminar algum trabalho IRL!

I managed to create an automation to generate MacOS and Linux versions, I hope it works
