### ISSUE TITLE
Downloading Russians subtitles instead of English subtitles

### ISSUE THREAD

**Issue by MGadAllah** [heliomarpm/udemy-downloader-gui#97]
### Udeler | Udemy Course Downloader

v1.11.6

### Running as Business Account

- [ ] Yes

### Steps to reproduce

1. Log in to my account.
2. Search for the course I want to download.
3. Click on the download icon.
4. Open the downloaded folder, and found all subtitles are Russian and not English.

### ✔️ Expected Behavior

English subtitle files

### ❌ Actual Behavior / Steps to Reproduce

1. Log in to my account.
2. Search for the course I want to download.
3. Click on the download icon.
4. Open the downloaded folder, and found all subtitles are Russian and not English.

**Comment by heliomarpm** [comment]
Perhaps this happens, if the course contains only Russian subtitles.
Could you check this on the Udemy platform please?
If this is not the case, check in the settings tab what is selected by default, if you can also let me know the name of the course.

**Comment by heliomarpm** [comment]
> Cant able to download DRM protected videos
> ![image](https://user-images.githubusercontent.com/127341559/223806010-cf319d40-d052-4c88-bbfa-4cc302c52faf.png)
> 

This tool does not download protected videos, is't an issue.
