### ISSUE TITLE
mac version doesn't download courses - drm protection

### ISSUE THREAD

**Issue by hachem9** [heliomarpm/udemy-downloader-gui#99]
### Udeler | Udemy Course Downloader

1.11.2

### Running as Business Account

- [ ] Yes

### Steps to reproduce

i downloaded the version of yesterday but the course stuck at 0kb/s and 0 out of 182 

### ✔️ Expected Behavior

course expected to start downloading nut it doesn't

### ❌ Actual Behavior / Steps to Reproduce

gg

**Comment by heliomarpm** [comment]
Please send me more details.
Screenshots, logger file and course name can help.

**Comment by hachem9** [comment]
thank you for your reply i open it now and it says contains drm protection and cannot be downloaded and ther's a red lock icon on the course image ,the course name is :
[Flutter - Firebase - MySQL : Multi-store App (Full - Deep)]
(https://www.udemy.com/course/flutter-multi-store/)

**Comment by heliomarpm** [comment]
> Infelizmente, neste caso, não temos nada a fazer, pois não é um problema.
A Udemy está protegendo muitos de seus cursos, desculpe.
